// infoq-scaffold-frontend-vue/src/views/system/user/authRole.vue
<template>
  <div class="p-2">
    <div class="panel">
      <h4 class="panel-title">基本信息</h4>
      <el-form :model="form" :inline="true">
        <el-row :gutter="10">
          <el-col :span="2.5">
            <el-form-item label="用户昵称" prop="nickName">
              <el-input v-model="form.nickName" disabled />
            </el-form-item>
          </el-col>
          <el-col :span="2.5">
            <el-form-item label="登录账号" prop="userName">
              <el-input v-model="form.userName" disabled />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
    </div>
    <div class="panel">
      <h4 class="panel-title">角色信息</h4>
      <div>
        <el-table
          ref="tableRef"
          v-loading="loading"
          border
          :row-key="getRowKey"
          :data="roles.slice((pageNum - 1) * pageSize, pageNum * pageSize)"
          @row-click="clickRow"
          @selection-change="handleSelectionChange"
        >
          <el-table-column label="序号" width="55" type="index" align="center">
            <template #default="scope">
              <span>{{ (pageNum - 1) * pageSize + scope.$index + 1 }}</span>
            </template>
          </el-table-column>
          <el-table-column type="selection" :reserve-selection="true" :selectable="checkSelectable" width="55"></el-table-column>
          <el-table-column label="角色编号" align="center" prop="roleId" />
          <el-table-column label="角色名称" align="center" prop="roleName" />
          <el-table-column label="权限字符" align="center" prop="roleKey" />
          <el-table-column label="创建时间" align="center" prop="createTime" width="180">
            <template #default="scope">
              <span>{{ proxy.parseTime(scope.row.createTime) }}</span>
            </template>
          </el-table-column>
        </el-table>
        <pagination v-show="total > 0" v-model:page="pageNum" v-model:limit="pageSize" :total="total" />
        <div style="text-align: center; margin-left: -120px; margin-top: 30px">
          <el-button type="primary" @click="submitForm()">提交</el-button>
          <el-button @click="close()">返回</el-button>
        </div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script setup name="AuthRole" lang="ts">
import { RoleVO } from '@/api/system/role/types';
import { getAuthRole, updateAuthRole } from '@/api/system/user';
import { UserForm } from '@/api/system/user/types';
import { RouteLocationNormalized } from 'vue-router';
import { parseTime } from '@/utils/scaffold';

const route = useRoute();
const { proxy } = getCurrentInstance() as ComponentInternalInstance;

const loading = ref(true);
const total = ref(0);
const pageNum = ref(1);
const pageSize = ref(10);
const roleIds = ref<Array<string | number>>([]);
const roles = ref<RoleVO[]>([]);
const form = ref<Partial<UserForm>>({
  nickName: undefined,
  userName: '',
  userId: undefined
});

const tableRef = ref<ElTableInstance>();

/** 单击选中行数据 */
const clickRow = (row: RoleVO) => {
  if (checkSelectable(row)) {
    row.flag = !row.flag;
    tableRef.value?.toggleRowSelection(row, row.flag);
  }
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: RoleVO[]) => {
  roleIds.value = selection.map((item) => item.roleId);
};
/** 保存选中的数据编号 */
const getRowKey = (row: RoleVO): string => {
  return String(row.roleId);
};
/** 检查角色状态 */
const checkSelectable = (row: RoleVO): boolean => {
  return row.status === '0';
};
/** 关闭按钮 */
const close = () => {
  const obj: RouteLocationNormalized = {
    fullPath: '',
    hash: '',
    matched: [],
    meta: undefined,
    name: undefined,
    params: undefined,
    query: undefined,
    redirectedFrom: undefined,
    path: '/system/user'
  };
  proxy?.$tab.closeOpenPage(obj);
};
/** 提交按钮 */
const submitForm = async () => {
  const userId = form.value.userId;
  const rIds = roleIds.value.join(',');
  await updateAuthRole({ userId: userId as string, roleIds: rIds });
  proxy?.$modal.msgSuccess('授权成功');
  close();
};

const getList = async () => {
  const userId = route.params && route.params.userId;
  if (userId) {
    loading.value = true;
    const res = await getAuthRole(userId as string);
    Object.assign(form.value, res.data.user);
    Object.assign(roles.value, res.data.roles);
    total.value = roles.value.length;
    await nextTick(() => {
      roles.value.forEach((row) => {
        if (row?.flag) {
          tableRef.value?.toggleRowSelection(row, true);
        }
      });
    });
    loading.value = false;
  }
};
onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/system/user/authRole.tsx
import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Col, Form, Input, Row, Space, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useLocation, useNavigate } from 'react-router-dom';
import { getAuthRole, updateAuthRole } from '@/api/system/user';
import type { UserForm } from '@/api/system/user/types';
import type { RoleVO } from '@/api/system/role/types';
import modal from '@/utils/modal';
import { resolveData, resolveRows } from '@/utils/api';

type AuthRoleResponse = {
  user: Partial<UserForm>;
  roles: RoleVO[];
};

const defaultResponse: AuthRoleResponse = {
  user: {},
  roles: []
};

export default function AuthRolePage() {
  const navigate = useNavigate();
  const location = useLocation();
  const userId = location.pathname.split('/').pop() || '';
  const [loading, setLoading] = useState(false);
  const [userInfo, setUserInfo] = useState<Partial<UserForm>>({});
  const [roles, setRoles] = useState<RoleVO[]>([]);
  const [selectedRoleIds, setSelectedRoleIds] = useState<Array<string | number>>([]);

  const loadData = async () => {
    if (!userId) {
      return;
    }
    setLoading(true);
    try {
      const response = (await getAuthRole(userId)) as unknown as { data?: AuthRoleResponse };
      const data = resolveData(response, defaultResponse);
      setUserInfo(data.user);
      setRoles(resolveRows({ data: data.roles }));
      setSelectedRoleIds(data.roles.filter((item) => item.flag).map((item) => item.roleId));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, [userId]);

  const columns = useMemo<ColumnsType<RoleVO>>(
    () => [
      {
        title: '序号',
        key: 'index',
        width: 70,
        align: 'center',
        render: (_value: unknown, _record: RoleVO, index: number) => index + 1
      },
      {
        title: '角色编号',
        dataIndex: 'roleId',
        width: 120,
        align: 'center'
      },
      {
        title: '角色名称',
        dataIndex: 'roleName',
        align: 'center'
      },
      {
        title: '权限字符',
        dataIndex: 'roleKey',
        align: 'center'
      },
      {
        title: '状态',
        dataIndex: 'status',
        width: 100,
        render: (value: string) => (value === '0' ? '正常' : '停用')
      },
      {
        title: '创建时间',
        dataIndex: 'createTime',
        width: 180,
        align: 'center'
      }
    ],
    []
  );

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      <Card title="基本信息">
        <Form layout="inline">
          <Row gutter={10} style={{ width: '100%' }}>
            <Col xs={24} md={8}>
              <Form.Item label="用户昵称" style={{ width: '100%', marginBottom: 0 }}>
                <Input value={userInfo.nickName} disabled />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item label="登录账号" style={{ width: '100%', marginBottom: 0 }}>
                <Input value={userInfo.userName} disabled />
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Card>

      <Card title="角色信息">
        <Table<RoleVO>
          rowKey="roleId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={roles}
          pagination={false}
          rowSelection={{
            selectedRowKeys: selectedRoleIds,
            getCheckboxProps: (record) => ({ disabled: record.status !== '0' }),
            onChange: (keys) => setSelectedRoleIds(keys as Array<string | number>)
          }}
        />
        <div style={{ textAlign: 'center', marginTop: 30 }}>
          <Space>
            <Button
              type="primary"
              onClick={async () => {
                await updateAuthRole({
                  userId,
                  roleIds: selectedRoleIds.join(',')
                });
                modal.msgSuccess('授权成功');
                navigate('/system/user');
              }}
            >
              提交
            </Button>
            <Button onClick={() => navigate('/system/user')}>返回</Button>
          </Space>
        </div>
      </Card>
    </Space>
  );
}
