// infoq-scaffold-frontend-weapp-react/src/pages/system-posts/index.tsx
import { View } from '@tarojs/components';
import Taro, { useDidShow } from '@tarojs/taro';
import {
  delPost,
  getDictLabel,
  getDicts,
  listPost,
  toDictOptions,
  type DictOption,
  type PostQuery,
  type PostVO
} from '@/api';
import { useState } from 'react';
import { AtInput, AtButton } from 'taro-ui';
import BottomNav from '../../components/bottom-nav';
import { EmptyNotice, KeyValueList, PaginationBar, RecordCard, StatusTag, FabButton } from '../../components/taro-ui-kit';
import { navigate, routes } from '../../utils/navigation';
import { handlePageError, showSuccess } from '../../utils/ui';
import { useSessionStore } from '../../store/session';
import './index.scss';

const createQuery = (pageNum = 1): PostQuery => ({
  pageNum,
  pageSize: 10,
  deptId: '',
  belongDeptId: '',
  postCode: '',
  postName: '',
  postCategory: '',
  status: ''
});

export default function SystemPostsPage() {
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);
  const [query, setQuery] = useState<PostQuery>(createQuery());
  const [list, setList] = useState<PostVO[]>([]);
  const [total, setTotal] = useState(0);
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);

  const canList = permissions.includes('system:post:list');
  const canAdd = permissions.includes('system:post:add');
  const canEdit = permissions.includes('system:post:edit');
  const canRemove = permissions.includes('system:post:remove');

  const loadPage = async (nextQuery = query) => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }
      const [statusResponse, listResponse] = await Promise.all([
        getDicts('sys_normal_disable'),
        canList ? listPost(nextQuery) : Promise.resolve({ rows: [], total: 0 })
      ]);
      setStatusOptions(toDictOptions(statusResponse.data));
      setList(listResponse.rows || []);
      setTotal(listResponse.total || 0);
    } catch (error) {
      await handlePageError(error, '岗位列表加载失败');
    }
  };

  useDidShow(() => {
    void loadPage();
  });

  const openCreate = () => {
    navigate(routes.postForm);
  };

  const openEdit = (postId: string | number) => {
    navigate(`${routes.postForm}?postId=${postId}`);
  };

  const handleDelete = async (postId: string | number) => {
    const modal = await Taro.showModal({
      title: '确认删除',
      content: `确定删除岗位 #${postId} 吗？`
    });
    if (!modal.confirm) return;
    try {
      await delPost(postId);
      await showSuccess('岗位已删除');
      await loadPage({ ...query });
    } catch (error) {
      await handlePageError(error, '岗位删除失败');
    }
  };

  return (
    <View className="list-container">
      <View className="search-section">
        <View className="search-card">
          <AtInput
            clear
            name="postName"
            placeholder="按岗位名称过滤"
            title="岗位名称"
            value={query.postName || ''}
            onChange={(value) => {
              setQuery((prev) => ({ ...prev, postName: String(value) }));
              return value;
            }}
          />
          <AtInput
            clear
            name="postCode"
            placeholder="按岗位编码过滤"
            title="岗位编码"
            value={query.postCode || ''}
            onChange={(value) => {
              setQuery((prev) => ({ ...prev, postCode: String(value) }));
              return value;
            }}
          />
          <View className="search-actions">
            <AtButton
              className="search-action-btn"
              type="secondary"
              onClick={() => {
                const nextQuery = createQuery();
                setQuery(nextQuery);
                void loadPage(nextQuery);
              }}
            >
              重置
            </AtButton>
            <AtButton
              className="search-action-btn"
              type="primary"
              onClick={() => void loadPage({ ...query, pageNum: 1 })}
            >
              查询
            </AtButton>
          </View>
        </View>
      </View>

      <View className="list-content">
        {!canList && <EmptyNotice message="当前账号没有访问权限" />}
        {canList && list.length === 0 && <EmptyNotice message="未查询到相关岗位" />}
        {canList && list.map((item) => (
          <RecordCard
            key={String(item.postId)}
            icon="calendar"
            title={item.postName || '未知岗位'}
            statusColor={item.status === '0' ? '#52c41a' : '#ff4d4f'}
            extra={
              <StatusTag 
                label={getDictLabel(statusOptions, item.status) || '未知'} 
                type={item.status === '0' ? 'success' : 'error'} 
              />
            }
            actions={[
              ...(canEdit ? [{ onClick: () => void openEdit(item.postId), title: '编辑' }] : []),
              ...(canRemove ? [{ 
                onClick: () => void handleDelete(item.postId), 
                title: '删除',
                danger: true 
              }] : [])
            ]}
          >
            <KeyValueList
              items={[
                { label: '岗位编码', value: item.postCode || '-' },
                { label: '所属部门', value: item.deptName || '-' },
                { label: '岗位类别', value: item.postCategory || '-' },
                { label: '显示顺序', value: String(item.postSort) }
              ]}
            />
          </RecordCard>
        ))}

        {canList && (
          <PaginationBar
            current={query.pageNum}
            pageSize={query.pageSize}
            total={total}
            onChange={(page) => {
              const nextQuery = { ...query, pageNum: page };
              setQuery(nextQuery);
              void loadPage(nextQuery);
            }}
          />
        )}
      </View>

      {canAdd && <FabButton onClick={() => openCreate()} />}
      
      <BottomNav active="admin" />
    </View>
  );
}

// infoq-scaffold-frontend-weapp-vue/src/pages/system-posts/index.vue
<template>
  <view class="list-container">
    <view class="search-section">
      <view class="search-card">
        <view class="search-field">
          <text class="field-label">岗位名称</text>
          <view class="field-input-box">
            <input v-model="query.postName" placeholder="按岗位名称过滤" placeholder-style="color: #94a3b8" />
          </view>
        </view>
        <view class="search-actions">
  <button class="secondary-btn search-action-btn" @click="handleReset">重置</button>
  <button class="primary-btn search-action-btn" @click="handleSearch">查询</button>
</view>
      </view>
    </view>

    <view class="list-content">
      <EmptyNotice v-if="!canList" message="暂无访问权限" />
      <EmptyNotice v-else-if="rows.length === 0" message="未查询到相关岗位" />
      
      <template v-if="canList">
        <RecordCard
          v-for="item in rows"
          :key="String(item.postId)"
          icon="calendar"
          :title="item.postName"
          :status-color="item.status === '0' ? '#52c41a' : '#ff4d4f'"
          :actions="getActions(item)"
        >
          <template #extra>
            <StatusTag 
              :label="item.status === '0' ? '正常' : '停用'" 
              :type="item.status === '0' ? 'success' : 'error'" 
            />
          </template>
          
          <KeyValueList
            :items="[
              { label: '岗位编码', value: item.postCode || '-' },
              { label: '显示顺序', value: String(item.postSort) },
              { label: '创建时间', value: item.createTime ? String(item.createTime).split(' ')[0] : '-' }
            ]"
          />
        </RecordCard>
      </template>
    </view>

    <FabButton v-if="canAdd" @click="openCreate" />
    
    <BottomNav active="admin" />
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { delPost, listPost, type PostQuery, type PostVO } from '@/api';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { navigate, routes } from '@/utils/navigation';
import { handlePageError, showSuccess } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

import BottomNav from '@/components/BottomNav.vue';
import EmptyNotice from '@/components/EmptyNotice.vue';
import KeyValueList from '@/components/KeyValueList.vue';
import RecordCard from '@/components/RecordCard.vue';
import StatusTag from '@/components/StatusTag.vue';
import FabButton from '@/components/FabButton.vue';

const sessionStore = useSessionStore();
const rows = ref<PostVO[]>([]);
const query = reactive<PostQuery>({
  pageNum: 1,
  pageSize: 20,
  postCode: '',
  postName: '',
  postCategory: '',
  status: ''
});

const canList = computed(() => sessionStore.permissions.includes('system:post:list'));
const canAdd = computed(() => sessionStore.permissions.includes('system:post:add'));
const canEdit = computed(() => sessionStore.permissions.includes('system:post:edit'));
const canRemove = computed(() => sessionStore.permissions.includes('system:post:remove'));

const loadData = async () => {
  if (!ensureAuthenticated()) return;
  try {
    await sessionStore.loadSession();
    const response = await listPost(query);
    rows.value = response.rows || [];
  } catch (error) {
    await handlePageError(error, '岗位加载失败');
  }
};

const handleSearch = () => {
  query.pageNum = 1;
  void loadData();
};

const handleReset = () => {
  query.postName = '';
  query.postCode = '';
  query.postCategory = '';
  query.pageNum = 1;
  void loadData();
};

const openCreate = () => navigate(routes.postForm);

const getActions = (item: PostVO) => {
  const actions = [];
  if (canEdit.value) {
    actions.push({ title: '编辑', onClick: () => navigate(`${routes.postForm}?postId=${item.postId}`) });
  }
  if (canRemove.value) {
    actions.push({ title: '删除', danger: true, onClick: () => removeItem(item.postId) });
  }
  return actions;
};

const removeItem = async (postId: string | number) => {
  const res = await uni.showModal({ title: '确认删除', content: '确定删除该岗位吗？' });
  if (!res.confirm) return;
  try {
    await delPost(postId);
    await showSuccess('删除成功');
    await loadData();
  } catch (error) {
    await handlePageError(error, '删除失败');
  }
};

onShow(() => {
  void loadData();
});
</script>

<style lang="scss">
@import './index.scss';
</style>
