// infoq-scaffold-frontend-weapp-vue/src/pages/admin/index.vue
<template>
  <view class="admin-container">
    <view class="admin-banner">
      <view class="banner-content">
        <view class="title">移动管理台</view>
        <view class="desc">AI-first 数字化管控中心</view>
      </view>
    </view>

    <view class="admin-content-wrapper">
      <!-- System Management -->
      <view class="admin-section card-container">
        <view class="card-header">
          <view class="card-title">系统管理</view>
          <view class="card-extra" v-if="systemModules.length">{{ systemModules.length }} 模块</view>
        </view>
        
        <view class="card-content">
          <view class="module-grid" v-if="systemModules.length">
            <view
              class="module-item"
              v-for="item in systemModules"
              :key="item.key"
              @click="navigate(item.url)"
            >
              <view class="icon-wrapper">
                <AppIcon :name="item.key" size="56" color="#1677ff" />
              </view>
              <text class="module-label">{{ item.title }}</text>
            </view>
          </view>
          <view class="empty-state" v-else>
            <text class="empty-text">无系统管理权限</text>
          </view>
        </view>
      </view>

      <!-- System Monitoring -->
      <view class="admin-section card-container">
        <view class="card-header">
          <view class="card-title">系统监控</view>
          <view class="card-extra" v-if="monitorModules.length">{{ monitorModules.length }} 指标</view>
        </view>
        
        <view class="card-content">
          <view class="module-grid" v-if="monitorModules.length">
            <view
              class="module-item"
              v-for="item in monitorModules"
              :key="item.key"
              @click="navigate(item.url)"
            >
              <view class="icon-wrapper monitor">
                <AppIcon :name="item.key" size="56" color="#52c41a" />
              </view>
              <text class="module-label">{{ item.title }}</text>
            </view>
          </view>
          <view class="empty-state" v-else>
            <text class="empty-text">无系统监控权限</text>
          </view>
        </view>
      </view>
    </view>

    <BottomNav active="admin" />
  </view>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import BottomNav from '@/components/BottomNav.vue';
import AppIcon from '@/components/AppIcon.vue';
import { monitorAdminModules, systemAdminModules } from '@/utils/admin';
import { navigate, routes } from '@/utils/navigation';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { handlePageError } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

const sessionStore = useSessionStore();

const systemModules = computed(() => systemAdminModules.filter((item) => sessionStore.permissions.includes(item.permission)));
const monitorModules = computed(() => monitorAdminModules.filter((item) => sessionStore.permissions.includes(item.permission)));

onShow(() => {
  if (!ensureAuthenticated()) {
    return;
  }
  void sessionStore.loadSession().catch(async (error) => {
    await handlePageError(error, '管理台加载失败');
    uni.reLaunch({ url: routes.login });
  });
});
</script>

<style lang="scss">
@import './index.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/admin/index.tsx
import { View, Text } from '@tarojs/components';
import Taro, { useDidShow } from '@tarojs/taro';
import { AtGrid, AtNoticebar } from 'taro-ui';
import BottomNav from '../../components/bottom-nav';
import { monitorAdminModules, systemAdminModules } from '../../utils/admin';
import { navigate, routes } from '../../utils/navigation';
import { handlePageError } from '../../utils/ui';
import { useSessionStore } from '../../store/session';
import './index.scss';

export default function AdminPage() {
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);

  useDidShow(() => {
    const run = async () => {
      try {
        const session = await loadSession();
        if (!session) {
          Taro.reLaunch({ url: routes.login });
        }
      } catch (error) {
        await handlePageError(error, '管理台加载失败');
      }
    };
    void run();
  });

  const systemModules = systemAdminModules.filter((item) => permissions.includes(item.permission));
  const monitorModules = monitorAdminModules.filter((item) => permissions.includes(item.permission));

  const iconMap: Record<string, string> = {
    users: 'user',
    roles: 'bookmark',
    depts: 'folder',
    posts: 'calendar',
    menus: 'menu',
    notices: 'message',
    online: 'eye',
    loginInfo: 'file-generic',
    operLog: 'list',
    cache: 'settings'
  };

  return (
    <View className="admin-container">
      <View className="admin-header">
        <Text className="title">移动管理台</Text>
        <Text className="desc">AI-first 数字化管控中心</Text>
      </View>

      <View className="card-container module-group">
        <View className="card-header">
          <Text className="card-title">系统管理</Text>
          <Text className="card-extra">{systemModules.length} 个活跃模块</Text>
        </View>
        <View className="card-content">
          {systemModules.length ? (
            <AtGrid
              columnNum={3}
              data={systemModules.map((item) => ({
                key: item.key,
                value: item.title,
                iconInfo: {
                  value: iconMap[item.key] || 'folder',
                  size: 28,
                  color: '#1677ff'
                }
              }))}
              hasBorder={false}
              onClick={(item) => {
                const target = systemModules.find((module) => module.key === item.key);
                if (target) {
                  navigate(target.url);
                }
              }}
            />
          ) : (
            <AtNoticebar single>当前账号没有系统管理权限</AtNoticebar>
          )}
        </View>
      </View>

      <View className="card-container module-group">
        <View className="card-header">
          <Text className="card-title">系统监控</Text>
          <Text className="card-extra">{monitorModules.length} 个监控指标</Text>
        </View>
        <View className="card-content">
          {monitorModules.length ? (
            <AtGrid
              columnNum={3}
              data={monitorModules.map((item) => ({
                key: item.key,
                value: item.title,
                iconInfo: {
                  value: iconMap[item.key] || 'eye',
                  size: 28,
                  color: '#1677ff'
                }
              }))}
              hasBorder={false}
              onClick={(item) => {
                const target = monitorModules.find((module) => module.key === item.key);
                if (target) {
                  navigate(target.url);
                }
              }}
            />
          ) : (
            <AtNoticebar single>当前账号没有系统监控权限</AtNoticebar>
          )}
        </View>
      </View>

      <BottomNav active="admin" />
    </View>
  );
}
