// infoq-scaffold-frontend-react/src/pages/system/menu/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { Button, Card, Col, Form, Input, InputNumber, Modal, Radio, Row, Select, Space, Table, Tooltip, Tree, TreeSelect } from 'antd';
import type { DataNode } from 'antd/es/tree';
import type { ColumnsType } from 'antd/es/table';
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import useDictOptions from '@/hooks/useDictOptions';
import { addMenu, cascadeDelMenu, delMenu, getMenu, listMenu, updateMenu } from '@/api/system/menu';
import type { MenuForm, MenuQuery, MenuVO } from '@/api/system/menu/types';
import RightToolbar from '@/components/RightToolbar';
import DictTag from '@/components/DictTag';
import SvgIcon from '@/components/SvgIcon';
import modal from '@/utils/modal';
import { handleTree } from '@/utils/scaffold';
import { resolveArrayData, resolveData } from '@/utils/api';

type MenuNode = MenuVO;

const initialQuery: MenuQuery = {
  keywords: '',
  menuName: '',
  status: ''
};

const initialForm: MenuForm = {
  menuId: undefined,
  parentId: 0,
  menuName: '',
  orderNum: 1,
  path: '',
  component: '',
  queryParam: '',
  isFrame: '1',
  isCache: '0',
  menuType: 'M' as never,
  visible: '0',
  status: '0',
  icon: '',
  remark: '',
  query: '',
  perms: ''
};

const toTreeSelectData = (nodes: MenuVO[]): DataNode[] =>
  nodes.map((node) => ({
    key: String(node.menuId),
    value: node.menuId,
    title: node.menuName,
    children: node.children?.length ? toTreeSelectData(node.children) : undefined
  }));

export default function MenuPage() {
  const [query, setQuery] = useState<MenuQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<MenuVO[]>([]);
  const [menuOptions, setMenuOptions] = useState<MenuVO[]>([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [checkedMenuIds, setCheckedMenuIds] = useState<Array<string | number>>([]);
  const [submitting, setSubmitting] = useState(false);
  const [form] = Form.useForm<MenuForm>();
  const menuId = Form.useWatch('menuId', form);
  const dict = useDictOptions('sys_show_hide', 'sys_normal_disable');

  const loadList = useCallback(async (nextQuery: MenuQuery = query) => {
    setLoading(true);
    try {
      const response = (await listMenu(nextQuery)) as unknown as { data?: MenuVO[] };
      const data = handleTree<MenuNode>(resolveArrayData(response), 'menuId');
      setList(data);
      setMenuOptions(data);
    } finally {
      setLoading(false);
    }
  }, [query]);

  useEffect(() => {
    loadList(initialQuery);
  }, [loadList]);

  const columns: ColumnsType<MenuVO> = [
    { title: '菜单名称', dataIndex: 'menuName', width: 160, ellipsis: true },
    {
      title: '图标',
      dataIndex: 'icon',
      width: 120,
      align: 'center',
      render: (value: string) =>
        value && value !== '#' ? (
          <SvgIcon iconClass={value} size={16} />
        ) : (
          '-'
        )
    },
    { title: '排序', dataIndex: 'orderNum', width: 60, align: 'center' },
    { title: '权限标识', dataIndex: 'perms' },
    { title: '组件路径', dataIndex: 'component' },
    {
      title: '状态',
      dataIndex: 'status',
      width: 80,
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_normal_disable || []} value={value} />
    },
    { title: '创建时间', dataIndex: 'createTime', width: 160, align: 'center' },
    {
      title: '操作',
      key: 'action',
      width: 180,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          <Tooltip title="修改">
            <Button type="link" icon={<EditOutlined />} onClick={() => handleEdit(record.menuId)} />
          </Tooltip>
          <Tooltip title="新增">
            <Button type="link" icon={<PlusOutlined />} onClick={() => handleAdd(record.menuId)} />
          </Tooltip>
          <Tooltip title="删除">
            <Button danger type="link" icon={<DeleteOutlined />} onClick={() => handleDelete(record.menuId, record.menuName)} />
          </Tooltip>
        </Space>
      )
    }
  ];

  const handleAdd = async (parentId?: string | number) => {
    const response = (await listMenu()) as unknown as { data?: MenuVO[] };
    const data = handleTree<MenuVO>(resolveArrayData(response), 'menuId');
    setMenuOptions(data);
    form.setFieldsValue({
      ...initialForm,
      parentId: parentId ?? 0
    });
    setDialogOpen(true);
  };

  const handleEdit = async (menuId?: string | number) => {
    if (!menuId) {
      return;
    }
    const allResponse = (await listMenu()) as unknown as { data?: MenuVO[] };
    setMenuOptions(handleTree<MenuVO>(resolveArrayData(allResponse), 'menuId'));
    const detailResponse = (await getMenu(menuId)) as unknown as { data?: MenuVO };
    form.setFieldsValue(resolveData(detailResponse, initialForm as unknown as MenuVO) as unknown as MenuForm);
    setDialogOpen(true);
  };

  const handleDelete = async (menuId?: string | number, menuName?: string) => {
    if (!menuId) {
      return;
    }
    const confirmed = await modal.confirm(`是否确认删除名称为 "${menuName || menuId}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delMenu(menuId);
    modal.msgSuccess('删除成功');
    loadList();
  };

  const handleSubmit = async () => {
    const values = await form.validateFields();
    setSubmitting(true);
    try {
      if (values.menuId) {
        await updateMenu(values);
      } else {
        await addMenu(values);
      }
      modal.msgSuccess('操作成功');
      setDialogOpen(false);
      loadList();
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="菜单名称" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入菜单名称"
                    value={query.menuName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, menuName: event.target.value }))}
                    onPressEnter={() => loadList(query)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="菜单状态"
                    value={query.status || undefined}
                    options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item style={{ marginBottom: 12 }}>
                  <Space>
                    <Button type="primary" icon={<SearchOutlined />} onClick={() => loadList(query)}>
                      搜索
                    </Button>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => {
                        setQuery(initialQuery);
                        loadList(initialQuery);
                      }}
                    >
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            <Button className="btn-plain-primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
              新增
            </Button>
            <Button danger icon={<DeleteOutlined />} onClick={() => setDeleteOpen(true)} style={{ borderColor: '#ffccc7' }}>
              级联删除
            </Button>
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList()} />
          </div>
        </div>

        <Table<MenuVO>
          rowKey="menuId"
          bordered
          loading={loading}
          columns={columns}
          dataSource={list}
          pagination={false}
          expandable={{
            rowExpandable: (record) => Array.isArray(record.children) && record.children.length > 0
          }}
        />
      </Card>

      <Modal
        width={860}
        open={dialogOpen}
        title={menuId ? '修改菜单' : '新增菜单'}
        confirmLoading={submitting}
        onCancel={() => setDialogOpen(false)}
        onOk={handleSubmit}
      >
        <Form form={form} layout="vertical" initialValues={initialForm}>
          <Form.Item label="上级菜单" name="parentId">
            <TreeSelect treeData={toTreeSelectData(menuOptions)} placeholder="选择上级菜单" allowClear treeDefaultExpandAll />
          </Form.Item>
          <Form.Item label="菜单类型" name="menuType">
            <Radio.Group
              options={[
                { label: '目录', value: 'M' },
                { label: '菜单', value: 'C' },
                { label: '按钮', value: 'F' }
              ]}
            />
          </Form.Item>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item label="菜单名称" name="menuName" rules={[{ required: true, message: '菜单名称不能为空' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="显示排序" name="orderNum" rules={[{ required: true, message: '菜单顺序不能为空' }]}>
                <InputNumber min={0} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="是否外链" name="isFrame">
                <Radio.Group
                  options={[
                    { label: '是', value: '0' },
                    { label: '否', value: '1' }
                  ]}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="路由地址" name="path" rules={[{ required: true, message: '路由地址不能为空' }]}>
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="组件路径" name="component">
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="权限字符" name="perms">
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="路由参数" name="queryParam">
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="是否缓存" name="isCache">
                <Radio.Group
                  options={[
                    { label: '缓存', value: '0' },
                    { label: '不缓存', value: '1' }
                  ]}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="显示状态" name="visible">
                <Radio.Group options={(dict.sys_show_hide || []).map((item) => ({ label: item.label, value: item.value }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="菜单状态" name="status">
                <Radio.Group options={(dict.sys_normal_disable || []).map((item) => ({ label: item.label, value: item.value }))} />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="图标" name="icon">
                <Input />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="激活路由" name="remark">
                <Input />
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Modal>

      <Modal
        open={deleteOpen}
        title="级联删除菜单"
        onCancel={() => setDeleteOpen(false)}
        onOk={async () => {
          if (checkedMenuIds.length === 0) {
            modal.msgWarning('请选择要删除的菜单');
            return;
          }
          await cascadeDelMenu(checkedMenuIds);
          modal.msgSuccess('删除成功');
          setDeleteOpen(false);
          setCheckedMenuIds([]);
          loadList();
        }}
      >
        <Tree
          checkable
          defaultExpandAll
          treeData={toTreeSelectData(menuOptions)}
          checkedKeys={checkedMenuIds.map(String)}
          onCheck={(keys) => {
            const nextKeys = Array.isArray(keys) ? keys : keys.checked;
            setCheckedMenuIds(nextKeys as Array<string | number>);
          }}
        />
      </Modal>
    </Space>
  );
}

// infoq-scaffold-frontend-vue/src/views/system/menu/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="菜单名称" prop="menuName">
              <el-input v-model="queryParams.menuName" placeholder="请输入菜单名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="菜单状态" clearable>
                <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:menu:add']" type="primary" plain icon="Plus" @click="handleAdd()">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:menu:remove']" type="danger" plain icon="Delete" @click="handleCascadeDelete" :loading="deleteLoading"
              >级联删除</el-button
            >
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table
        ref="menuTableRef"
        v-loading="loading"
        :data="menuList"
        row-key="menuId"
        border
        :tree-props="{ children: 'children', hasChildren: 'hasChildren' }"
        :default-expand-all="false"
        lazy
        :load="getChildrenList"
        :expand-change="expandMenuHandle"
      >
        <el-table-column prop="menuName" label="菜单名称" :show-overflow-tooltip="true" width="160"></el-table-column>
        <el-table-column prop="icon" label="图标" align="center" width="100">
          <template #default="scope">
            <svg-icon :icon-class="scope.row.icon" />
          </template>
        </el-table-column>
        <el-table-column prop="orderNum" label="排序" width="60"></el-table-column>
        <el-table-column prop="perms" label="权限标识" :show-overflow-tooltip="true"></el-table-column>
        <el-table-column prop="component" label="组件路径" :show-overflow-tooltip="true"></el-table-column>
        <el-table-column prop="status" label="状态" width="80">
          <template #default="scope">
            <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="创建时间" align="center" prop="createTime">
          <template #default="scope">
            <span>{{ scope.row.createTime }}</span>
          </template>
        </el-table-column>
        <el-table-column fixed="right" label="操作" width="180">
          <template #default="scope">
            <el-tooltip content="修改" placement="top">
              <el-button v-hasPermi="['system:menu:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)" />
            </el-tooltip>
            <el-tooltip content="新增" placement="top">
              <el-button v-hasPermi="['system:menu:add']" link type="primary" icon="Plus" @click="handleAdd(scope.row)" />
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['system:menu:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)" />
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="dialog.visible" :title="dialog.title" destroy-on-close append-to-bod width="750px">
      <el-form ref="menuFormRef" :model="form" :rules="rules" label-width="100px">
        <el-row>
          <el-col :span="24">
            <el-form-item label="上级菜单">
              <el-tree-select
                v-model="form.parentId"
                :data="menuOptions"
                :props="menuTreeSelectProps"
                value-key="menuId"
                placeholder="选择上级菜单"
                check-strictly
              />
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="菜单类型" prop="menuType">
              <el-radio-group v-model="form.menuType">
                <el-radio value="M">目录</el-radio>
                <el-radio value="C">菜单</el-radio>
                <el-radio value="F">按钮</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="24">
            <el-form-item label="菜单图标" prop="icon">
              <!-- 图标选择器 -->
              <icon-select v-model="form.icon" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="菜单名称" prop="menuName">
              <el-input v-model="form.menuName" placeholder="请输入菜单名称" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="显示排序" prop="orderNum">
              <el-input-number v-model="form.orderNum" controls-position="right" :min="0" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item>
              <template #label>
                <span>
                  <el-tooltip content="选择是外链则路由地址需要以`http(s)://`开头" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon> </el-tooltip
                  >是否外链
                </span>
              </template>
              <el-radio-group v-model="form.isFrame">
                <el-radio value="0">是</el-radio>
                <el-radio value="1">否</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item prop="path">
              <template #label>
                <span>
                  <el-tooltip content="访问的路由地址，如：`user`，如外网地址需内链访问则以`http(s)://`开头" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  路由地址
                </span>
              </template>
              <el-input v-model="form.path" placeholder="请输入路由地址" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType === 'C'" :span="12">
            <el-form-item prop="component">
              <template #label>
                <span>
                  <el-tooltip content="访问的组件路径，如：`system/user/index`，默认在`views`目录下" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  组件路径
                </span>
              </template>
              <el-input v-model="form.component" placeholder="请输入组件路径" />
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'M'" :span="12">
            <el-form-item>
              <el-input v-model="form.perms" placeholder="请输入权限标识" maxlength="100" />
              <template #label>
                <span>
                  <el-tooltip content="控制器中定义的权限字符，如：@SaCheckPermission('system:user:list')" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  权限字符
                </span>
              </template>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType === 'C'" :span="12">
            <el-form-item>
              <el-input v-model="form.queryParam" placeholder="请输入路由参数" maxlength="255" />
              <template #label>
                <span>
                  <el-tooltip content='访问路由的默认传递参数，如：`{"id": 1, "name": "ry"}`' placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  路由参数
                </span>
              </template>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType === 'C'" :span="12">
            <el-form-item>
              <template #label>
                <span>
                  <el-tooltip content="选择是则会被`keep-alive`缓存，需要匹配组件的`name`和地址保持一致" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  是否缓存
                </span>
              </template>
              <el-radio-group v-model="form.isCache">
                <el-radio value="0">缓存</el-radio>
                <el-radio value="1">不缓存</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col v-if="form.menuType !== 'F'" :span="12">
            <el-form-item>
              <template #label>
                <span>
                  <el-tooltip content="选择隐藏则路由将不会出现在侧边栏，但仍然可以访问" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  显示状态
                </span>
              </template>
              <el-radio-group v-model="form.visible">
                <el-radio v-for="dict in sys_show_hide" :key="dict.value" :value="dict.value">{{ dict.label }} </el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item>
              <template #label>
                <span>
                  <el-tooltip content="选择停用则路由将不会出现在侧边栏，也不能被访问" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  菜单状态
                </span>
              </template>
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :value="dict.value">
                  {{ dict.label }}
                </el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col v-if="form.visible !== '0'" :span="12">
            <el-form-item label="激活路径" prop="form.remark">
              <template #label>
                <span>
                  <el-tooltip content="隐藏菜单填写默认激活路由，比如激活父菜单的路由 /system/user" placement="top">
                    <el-icon>
                      <question-filled />
                    </el-icon>
                  </el-tooltip>
                  激活路由
                </span>
              </template>
              <el-input v-model="form.remark" placeholder="请输入激活路径" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>

    <el-dialog v-model="deleteDialog.visible" :title="deleteDialog.title" destroy-on-close append-to-bod width="750px">
      <el-tree
        ref="menuTreeRef"
        class="tree-border"
        :data="menuOptions"
        show-checkbox
        node-key="menuId"
        :check-strictly="false"
        empty-text="加载中，请稍候"
        :default-expanded-keys="[0]"
        :props="menuTreeSelectProps"
      />
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitDeleteForm" :loading="deleteLoading">确 定</el-button>
          <el-button @click="cancelCascade">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Menu" lang="ts">
import { addMenu, cascadeDelMenu, delMenu, getMenu, listMenu, updateMenu } from '@/api/system/menu';
import { MenuForm, MenuQuery, MenuVO } from '@/api/system/menu/types';
import { MenuTypeEnum } from '@/enums/MenuTypeEnum';
import { toDictRefs } from '@/utils/dict';

interface MenuOptionsType {
  menuId: number;
  menuName: string;
  children: MenuOptionsType[] | undefined;
}

interface MenuExpandEntry {
  row: MenuVO;
  treeNode: unknown;
  resolve: (data: MenuVO[]) => void;
}

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_show_hide, sys_normal_disable } = toDictRefs(
  (proxy?.useDict('sys_show_hide', 'sys_normal_disable') ?? {}) as Record<'sys_show_hide' | 'sys_normal_disable', DictDataOption[]>
);

const menuList = ref<MenuVO[]>([]);
const menuChildrenListMap = ref<Record<string | number, MenuVO[]>>({});
const menuExpandMap = ref<Record<string | number, MenuExpandEntry | undefined>>({});
const loading = ref(true);
const showSearch = ref(true);
const menuOptions = ref<MenuOptionsType[]>([]);
const menuTreeSelectProps = { value: 'menuId', label: 'menuName', children: 'children' } as const;

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const queryFormRef = ref<ElFormInstance>();
const menuFormRef = ref<ElFormInstance>();
const initFormData = {
  path: '',
  menuId: undefined,
  parentId: 0,
  menuName: '',
  icon: '',
  menuType: MenuTypeEnum.M,
  orderNum: 1,
  isFrame: '1',
  isCache: '0',
  visible: '0',
  status: '0'
};
const data = reactive<PageData<MenuForm, MenuQuery>>({
  form: { ...initFormData },
  queryParams: {
    menuName: undefined,
    status: undefined
  },
  rules: {
    menuName: [{ required: true, message: '菜单名称不能为空', trigger: 'blur' }],
    orderNum: [{ required: true, message: '菜单顺序不能为空', trigger: 'blur' }],
    path: [{ required: true, message: '路由地址不能为空', trigger: 'blur' }]
  }
});

const menuTableRef = ref<ElTableInstance>();

const { queryParams, form, rules } = toRefs<PageData<MenuForm, MenuQuery>>(data);

/** 获取子菜单列表 */
const getChildrenList = async (row: MenuVO, treeNode: unknown, resolve: (data: MenuVO[]) => void) => {
  menuExpandMap.value[row.menuId] = { row, treeNode, resolve };
  const children = menuChildrenListMap.value[row.menuId] || [];
  // 菜单的子菜单清空后关闭展开
  if (children.length == 0) {
    // fix: 处理当菜单只有一个子菜单并被删除，需要将父菜单的展开状态关闭
    menuTableRef.value?.updateKeyChildren(row.menuId, children);
  }
  resolve(children);
};

/** 收起菜单时从menuExpandMap中删除对应菜单id数据 */
const expandMenuHandle = async (row: MenuVO, expanded: boolean) => {
  if (!expanded) {
    menuExpandMap.value[row.menuId] = undefined;
  }
};

/** 刷新展开的菜单数据 */
const refreshLoadTree = (parentId: string | number) => {
  const entry = menuExpandMap.value[parentId];
  if (entry) {
    const { row, treeNode, resolve } = entry;
    getChildrenList(row, treeNode, resolve);
    if (row.parentId) {
      const grandpaMenu = menuExpandMap.value[row.parentId];
      if (grandpaMenu) {
        getChildrenList(grandpaMenu.row, grandpaMenu.treeNode, grandpaMenu.resolve);
      }
    }
  }
};

/** 重新加载所有已展开的菜单的数据 */
const refreshAllExpandMenuData = () => {
  for (const menuId in menuExpandMap.value) {
    refreshLoadTree(menuId);
  }
};

/** 查询菜单列表 */
const getList = async () => {
  loading.value = true;
  const res = await listMenu(queryParams.value);

  const tempMap = {};
  // 存储 父菜单:子菜单列表
  for (const menu of res.data) {
    const parentId = menu.parentId;
    if (!tempMap[parentId]) {
      tempMap[parentId] = [];
    }
    tempMap[parentId].push(menu);
  }
  // 创建一个当前所有 menuId 的 Set，用于查找父菜单是否存在于当前数据中
  const menuIdSet = new Set();
  // 设置有没有子菜单
  for (const menu of res.data) {
    menu['hasChildren'] = tempMap[menu.menuId]?.length > 0;
    menuIdSet.add(menu.menuId);
  }
  menuChildrenListMap.value = tempMap;
  // 找出所有父ID不在当前菜单ID集合中的菜单项，作为新的顶层菜单
  menuList.value = res.data.filter((menu) => !menuIdSet.has(menu.parentId));
  // 根据新数据重新加载子菜单数据
  refreshAllExpandMenuData();
  loading.value = false;
};
/** 查询菜单下拉树结构 */
const getTreeselect = async () => {
  menuOptions.value = [];
  const response = await listMenu();
  const menu: MenuOptionsType = { menuId: 0, menuName: '主类目', children: [] };
  menu.children = proxy?.handleTree<MenuOptionsType>(response.data, 'menuId');
  menuOptions.value.push(menu);
};
/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};
/** 表单重置 */
const reset = () => {
  form.value = { ...initFormData };
  menuFormRef.value?.resetFields();
};

/** 搜索按钮操作 */
const handleQuery = () => {
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};
/** 新增按钮操作 */
const handleAdd = (row?: MenuVO) => {
  reset();
  getTreeselect();
  row && row.menuId ? (form.value.parentId = row.menuId) : (form.value.parentId = 0);
  dialog.visible = true;
  dialog.title = '添加菜单';
};
/** 修改按钮操作 */
const handleUpdate = async (row: MenuVO) => {
  reset();
  await getTreeselect();
  if (row.menuId) {
    const { data } = await getMenu(row.menuId);
    form.value = data;
  }
  dialog.visible = true;
  dialog.title = '修改菜单';
};
/** 提交按钮 */
const submitForm = () => {
  menuFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      form.value.menuId ? await updateMenu(form.value) : await addMenu(form.value);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};
/** 删除按钮操作 */
const handleDelete = async (row: MenuVO) => {
  await proxy?.$modal.confirm('是否确认删除名称为"' + row.menuName + '"的数据项?');
  await delMenu(row.menuId);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

const deleteLoading = ref<boolean>(false);
const menuTreeRef = ref<ElTreeInstance>();

const deleteDialog = reactive<DialogOption>({
  visible: false,
  title: '级联删除菜单'
});

/** 级联删除按钮操作 */
const handleCascadeDelete = () => {
  menuTreeRef.value?.setCheckedKeys([]);
  getTreeselect();
  deleteDialog.visible = true;
};

/** 取消按钮 */
const cancelCascade = () => {
  menuTreeRef.value?.setCheckedKeys([]);
  deleteDialog.visible = false;
};

/** 删除提交按钮 */
const submitDeleteForm = async () => {
  const menuIds = menuTreeRef.value?.getCheckedKeys() || [];
  if (menuIds.length <= 0) {
    proxy?.$modal.msgWarning('请选择要删除的菜单');
    return;
  }

  deleteLoading.value = true;
  await cascadeDelMenu(menuIds).finally(() => (deleteLoading.value = false));
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
  deleteDialog.visible = false;
};

onMounted(() => {
  getList();
});
</script>

<style scoped lang="scss">
.tree-border {
  height: 300px;
  overflow: auto;
}
</style>
