// infoq-scaffold-frontend-weapp-vue/src/pages/system-roles/form/index.vue
<template>
  <view class="page-wrap">
    <view class="form-section">
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">基本信息</text>
        </view>
        <view class="card-content" style="padding: 0">
          <view class="form-item-modern">
            <text class="form-label">角色名称</text>
            <input class="form-input-plain" v-model="form.roleName" placeholder="请输入角色名称" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">角色标识</text>
            <input class="form-input-plain" v-model="form.roleKey" placeholder="请输入角色标识" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">显示排序</text>
            <input class="form-input-plain" v-model.number="form.roleSort" type="number" placeholder="请输入排序" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>

      <view class="card-container">
        <view class="card-header">
          <text class="card-title">状态与备注</text>
        </view>
        <view class="card-content">
          <view class="form-item-vertical">
            <text class="item-label">状态</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in statusOptions"
                :key="item.value"
                :class="['radio-option-item', form.status === item.value ? 'active' : '']"
                @click="form.status = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.status === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>

          <view class="form-item-vertical" style="margin-top: 32rpx">
            <text class="item-label">备注说明</text>
            <textarea class="form-textarea" v-model="form.remark" placeholder="请输入备注" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>
    </view>

    <!-- 操作按钮 -->
    <view class="action-section">
      <button class="primary-btn save-btn" :loading="submitting" @click="save">保 存</button>
      <button class="secondary-btn cancel-btn" @click="backOr(routes.roles)">取 消</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { addRole, getRole, updateRole, getDicts, toDictOptions, type RoleForm, type DictOption } from '@/api';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { backOr, routes } from '@/utils/navigation';
import { handlePageError, showSuccess } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

const sessionStore = useSessionStore();
const roleId = ref('');
const submitting = ref(false);
const statusOptions = ref<DictOption[]>([]);

const form = reactive<RoleForm>({
  roleName: '',
  roleKey: '',
  roleSort: 0,
  status: '0',
  remark: '',
  menuIds: [],
  deptIds: []
});

const isEdit = computed(() => Boolean(roleId.value));

const loadData = async () => {
  try {
    const statusRes = await getDicts('sys_normal_disable');
    statusOptions.value = toDictOptions(statusRes.data);

    if (roleId.value) {
      const response = await getRole(roleId.value);
      Object.assign(form, response.data || {});
    }
  } catch (error) {
    await handlePageError(error, '角色信息加载失败');
  }
};

const save = async () => {
  if (!form.roleName?.trim() || !form.roleKey?.trim()) {
    await uni.showToast({ title: '角色名称和标识不能为空', icon: 'none' });
    return;
  }
  submitting.value = true;
  try {
    if (!ensureAuthenticated()) return;
    await sessionStore.loadSession();
    if (isEdit.value) {
      form.roleId = roleId.value;
      await updateRole(form);
    } else {
      await addRole(form);
    }
    await showSuccess('保存成功');
    backOr(routes.roles);
  } catch (error) {
    await handlePageError(error, '角色保存失败');
  } finally {
    submitting.value = false;
  }
};

onLoad((query) => {
  if (!ensureAuthenticated()) return;
  roleId.value = String(query?.roleId || '').trim();
  loadData();
});
</script>

<style lang="scss">
@import '@/styles/common.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/system-roles/form/index.tsx
import { View, Text } from '@tarojs/components';
import Taro, { useDidShow, useRouter } from '@tarojs/taro';
import {
  addRole,
  getDicts,
  getRole,
  toDictOptions,
  updateRole,
  type DictOption,
  type RoleForm
} from '@/api';
import { useState } from 'react';
import { AtButton, AtInput, AtTextarea } from 'taro-ui';
import { handlePageError, showSuccess } from '../../../utils/ui';
import { useSessionStore } from '../../../store/session';
import { routes } from '../../../utils/navigation';
import './index.scss';

const createForm = (): RoleForm => ({
  roleId: undefined,
  roleName: '',
  roleKey: '',
  roleSort: 1,
  status: '0',
  remark: ''
});

export default function RoleFormPage() {
  const router = useRouter();
  const roleId = router.params.roleId;
  const loadSession = useSessionStore((state) => state.loadSession);
  const [form, setForm] = useState<RoleForm>(createForm());
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const loadData = async () => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }

      const statusRes = await getDicts('sys_normal_disable');
      setStatusOptions(toDictOptions(statusRes.data));

      if (roleId) {
        const response = await getRole(roleId);
        const data = response.data;
        setForm({
          roleId: data.roleId,
          roleName: data.roleName,
          roleKey: data.roleKey,
          roleSort: data.roleSort,
          status: data.status || '0',
          remark: data.remark || ''
        });
      }
    } catch (error) {
      await handlePageError(error, '加载失败');
    }
  };

  useDidShow(() => {
    void loadData();
  });

  const handleSave = async () => {
    if (!form.roleName.trim()) {
      await Taro.showToast({ title: '请输入角色名称', icon: 'none' });
      return;
    }
    if (!form.roleKey.trim()) {
      await Taro.showToast({ title: '请输入权限字符', icon: 'none' });
      return;
    }

    setSubmitting(true);
    try {
      if (roleId) {
        await updateRole(form);
      } else {
        await addRole(form);
      }
      await showSuccess(roleId ? '角色已更新' : '角色已创建');
      Taro.navigateBack();
    } catch (error) {
      await handlePageError(error, '保存失败');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <View className="role-form-container">
      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <AtInput
              name="roleName"
              title="角色名称"
              placeholder="请输入角色名称"
              value={form.roleName}
              onChange={(v) => { setForm(p => ({ ...p, roleName: String(v) })); return v; }}
            />
            <AtInput
              name="roleKey"
              title="权限字符"
              placeholder="请输入权限字符"
              value={form.roleKey}
              onChange={(v) => { setForm(p => ({ ...p, roleKey: String(v) })); return v; }}
            />
            <AtInput
              name="roleSort"
              title="显示顺序"
              type="number"
              placeholder="请输入显示顺序"
              value={String(form.roleSort)}
              onChange={(v) => { setForm(p => ({ ...p, roleSort: Number(v) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">状态</Text>
          </View>
          <View className="card-content">
            <View className="radio-options-horizontal">
              {statusOptions.map((item) => (
                <View
                  key={item.value}
                  className={`radio-option-item ${form.status === item.value ? 'active' : ''}`}
                  onClick={() => setForm((prev) => ({ ...prev, status: item.value }))}
                >
                  <View className="radio-circle">
                    {form.status === item.value && <View className="radio-inner" />}
                  </View>
                  <Text className="radio-label">{item.label}</Text>
                </View>
              ))}
            </View>
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">备注</Text>
          </View>
          <View className="card-content">
            <AtTextarea
              height={200}
              count={false}
              placeholder="请输入备注说明"
              value={form.remark || ''}
              onChange={(value) => setForm((prev) => ({ ...prev, remark: value }))}
            />
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" loading={submitting} onClick={() => void handleSave()}>
          保存角色
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => Taro.navigateBack()}>
          返回
        </AtButton>
      </View>
    </View>
  );
}
