// infoq-scaffold-frontend-vue/src/views/monitor/online/index.vue
<template>
  <div class="p-2">
    <div class="mb-[10px]">
      <el-card shadow="hover">
        <el-form ref="queryFormRef" :model="queryParams" :inline="true">
          <el-form-item label="登录地址" prop="ipaddr">
            <el-input v-model="queryParams.ipaddr" placeholder="请输入登录地址" clearable @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item label="用户名称" prop="userName">
            <el-input v-model="queryParams.userName" placeholder="请输入用户名称" clearable @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
          </el-form-item>
        </el-form>
      </el-card>
    </div>
    <el-card shadow="hover">
      <el-table
        v-loading="loading"
        border
        :data="onlineList.slice((queryParams.pageNum - 1) * queryParams.pageSize, queryParams.pageNum * queryParams.pageSize)"
        style="width: 100%"
      >
        <el-table-column label="序号" width="50" type="index" align="center">
          <template #default="scope">
            <span>{{ (queryParams.pageNum - 1) * queryParams.pageSize + scope.$index + 1 }}</span>
          </template>
        </el-table-column>
        <el-table-column label="会话编号" align="center" prop="tokenId" :show-overflow-tooltip="true" />
        <el-table-column label="登录名称" align="center" prop="userName" :show-overflow-tooltip="true" />
        <el-table-column label="客户端" align="center" prop="clientKey" :show-overflow-tooltip="true" />
        <el-table-column label="设备类型" align="center">
          <template #default="scope">
            <dict-tag :options="sys_device_type" :value="scope.row.deviceType" />
          </template>
        </el-table-column>
        <el-table-column label="所属部门" align="center" prop="deptName" :show-overflow-tooltip="true" />
        <el-table-column label="主机" align="center" prop="ipaddr" :show-overflow-tooltip="true" />
        <el-table-column label="登录地点" align="center" prop="loginLocation" :show-overflow-tooltip="true" />
        <el-table-column label="操作系统" align="center" prop="os" :show-overflow-tooltip="true" />
        <el-table-column label="浏览器" align="center" prop="browser" :show-overflow-tooltip="true" />
        <el-table-column label="登录时间" align="center" prop="loginTime" width="180">
          <template #default="scope">
            <span>{{ proxy.parseTime(scope.row.loginTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="强退" placement="top">
              <el-button v-hasPermi="['monitor:online:forceLogout']" link type="primary" icon="Delete" @click="handleForceLogout(scope.row)">
              </el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" />
    </el-card>
  </div>
</template>

<script setup name="Online" lang="ts">
import { forceLogout, list as initData } from '@/api/monitor/online';
import { OnlineQuery, OnlineVO } from '@/api/monitor/online/types';
import api from '@/api/system/user';
import { to } from 'await-to-js';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_device_type } = toDictRefs((proxy?.useDict('sys_device_type') ?? {}) as Record<'sys_device_type', DictDataOption[]>);

const onlineList = ref<OnlineVO[]>([]);
const loading = ref(true);
const total = ref(0);

const queryFormRef = ref<ElFormInstance>();

const queryParams = ref<OnlineQuery>({
  pageNum: 1,
  pageSize: 10,
  ipaddr: '',
  userName: ''
});

/** 查询登录日志列表 */
const getList = async () => {
  loading.value = true;
  const res = await initData(queryParams.value);
  onlineList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};
/** 强退按钮操作 */
const handleForceLogout = async (row: OnlineVO) => {
  const [err] = await to(proxy?.$modal.confirm('是否确认强退名称为"' + row.userName + '"的用户?'));
  if (!err) {
    await forceLogout(row.tokenId);
    await getList();
    proxy?.$modal.msgSuccess('删除成功');
  }
};

onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/monitor/online/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Button, Card, Col, Form, Input, Row, Space, Table, Tooltip } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { DeleteOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import useDictOptions from '@/hooks/useDictOptions';
import { forceLogout, list } from '@/api/monitor/online';
import type { OnlineQuery, OnlineVO } from '@/api/monitor/online/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import modal from '@/utils/modal';
import { parseTime } from '@/utils/scaffold';

type OnlineRow = OnlineVO & {
  clientKey?: string;
  deviceType?: string;
};

const initialQuery: OnlineQuery = {
  pageNum: 1,
  pageSize: 10,
  ipaddr: '',
  userName: ''
};

export default function OnlinePage() {
  const [query, setQuery] = useState<OnlineQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [listData, setListData] = useState<OnlineRow[]>([]);
  const [total, setTotal] = useState(0);
  const dict = useDictOptions('sys_device_type');

  const loadList = useCallback(async (nextQuery: OnlineQuery = query) => {
    setLoading(true);
    try {
      const response = await list(nextQuery);
      setListData(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, [query]);

  useEffect(() => {
    loadList(initialQuery);
  }, [loadList]);

  const columns = useMemo<ColumnsType<OnlineRow>>(
    () => [
      {
        title: '序号',
        key: 'index',
        width: 50,
        align: 'center',
        render: (_, __, index) => (query.pageNum - 1) * query.pageSize + index + 1
      },
      {
        title: '会话编号',
        dataIndex: 'tokenId',
        align: 'center',
        ellipsis: true
      },
      {
        title: '登录名称',
        dataIndex: 'userName',
        align: 'center',
        ellipsis: true
      },
      {
        title: '客户端',
        dataIndex: 'clientKey',
        align: 'center',
        ellipsis: true
      },
      {
        title: '设备类型',
        dataIndex: 'deviceType',
        align: 'center',
        render: (value: string) => <DictTag options={dict.sys_device_type || []} value={value} />
      },
      {
        title: '所属部门',
        dataIndex: 'deptName',
        align: 'center',
        ellipsis: true
      },
      {
        title: '主机',
        dataIndex: 'ipaddr',
        align: 'center',
        ellipsis: true
      },
      {
        title: '登录地点',
        dataIndex: 'loginLocation',
        align: 'center',
        ellipsis: true
      },
      {
        title: '操作系统',
        dataIndex: 'os',
        align: 'center',
        ellipsis: true
      },
      {
        title: '浏览器',
        dataIndex: 'browser',
        align: 'center',
        ellipsis: true
      },
      {
        title: '登录时间',
        dataIndex: 'loginTime',
        align: 'center',
        width: 180,
        render: (value: string | number) => parseTime(value)
      },
      {
        title: '操作',
        key: 'action',
        width: 80,
        align: 'center',
        render: (_, record) => (
          <Tooltip title="强退">
            <Button
              className="table-action-link"
              type="link"
              icon={<DeleteOutlined />}
              onClick={async () => {
                const confirmed = await modal.confirm(`是否确认强退名称为 "${record.userName}" 的用户？`);
                if (!confirmed) {
                  return;
                }
                await forceLogout(record.tokenId);
                modal.msgSuccess('删除成功');
                loadList();
              }}
            />
          </Tooltip>
        )
      }
    ],
    [dict.sys_device_type, loadList, query.pageNum, query.pageSize]
  );

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      <Card>
        <Form layout="inline" className="query-form">
          <Row gutter={16} style={{ width: '100%' }}>
            <Col xs={24} md={12} xl={6}>
              <Form.Item label="登录地址" style={{ width: '100%', marginBottom: 12 }}>
                <Input
                  allowClear
                  placeholder="请输入登录地址"
                  value={query.ipaddr}
                  onChange={(event) => setQuery((prev) => ({ ...prev, ipaddr: event.target.value }))}
                  onPressEnter={() => {
                    const next = { ...query, pageNum: 1 };
                    setQuery(next);
                    loadList(next);
                  }}
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={12} xl={6}>
              <Form.Item label="用户名称" style={{ width: '100%', marginBottom: 12 }}>
                <Input
                  allowClear
                  placeholder="请输入用户名称"
                  value={query.userName}
                  onChange={(event) => setQuery((prev) => ({ ...prev, userName: event.target.value }))}
                  onPressEnter={() => {
                    const next = { ...query, pageNum: 1 };
                    setQuery(next);
                    loadList(next);
                  }}
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={12} xl={6}>
              <Form.Item style={{ marginBottom: 12 }}>
                <Space>
                  <Button
                    type="primary"
                    icon={<SearchOutlined />}
                    onClick={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next);
                    }}
                  >
                    搜索
                  </Button>
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={() => {
                      setQuery(initialQuery);
                      loadList(initialQuery);
                    }}
                  >
                    重置
                  </Button>
                </Space>
              </Form.Item>
            </Col>
          </Row>
        </Form>
      </Card>

      <Card>
        <Table<OnlineRow> rowKey="tokenId" bordered loading={loading} columns={columns} dataSource={listData} pagination={false} />
        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next);
          }}
        />
      </Card>
    </Space>
  );
}
