// infoq-scaffold-frontend-vue/src/views/monitor/operLog/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="操作地址" prop="operIp">
              <el-input v-model="queryParams.operIp" placeholder="请输入操作地址" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="系统模块" prop="title">
              <el-input v-model="queryParams.title" placeholder="请输入系统模块" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="操作人员" prop="operName">
              <el-input v-model="queryParams.operName" placeholder="请输入操作人员" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="类型" prop="businessType">
              <el-select v-model="queryParams.businessType" placeholder="操作类型" clearable>
                <el-option v-for="dict in sys_oper_type" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="操作状态" clearable>
                <el-option v-for="dict in sys_common_status" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="操作时间" style="width: 308px">
              <el-date-picker
                v-model="dateRange"
                value-format="YYYY-MM-DD HH:mm:ss"
                type="daterange"
                range-separator="-"
                start-placeholder="开始日期"
                end-placeholder="结束日期"
                :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
              ></el-date-picker>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:operLog:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:operLog:remove']" type="danger" plain icon="WarnTriangleFilled" @click="handleClean">清空</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:operLog:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table
        ref="operLogTableRef"
        v-loading="loading"
        :data="operLogList"
        border
        :default-sort="defaultSort"
        @selection-change="handleSelectionChange"
        @sort-change="handleSortChange"
      >
        <el-table-column type="selection" width="50" align="center" />
        <el-table-column label="日志编号" align="center" prop="operId" />
        <el-table-column label="系统模块" align="center" prop="title" :show-overflow-tooltip="true" />
        <el-table-column label="操作类型" align="center" prop="businessType">
          <template #default="scope">
            <dict-tag :options="sys_oper_type" :value="scope.row.businessType" />
          </template>
        </el-table-column>
        <el-table-column
          label="操作人员"
          align="center"
          width="110"
          prop="operName"
          :show-overflow-tooltip="true"
          sortable="custom"
          :sort-orders="['descending', 'ascending']"
        />
        <el-table-column label="部门" align="center" prop="deptName" width="130" :show-overflow-tooltip="true" />
        <el-table-column label="操作地址" align="center" prop="operIp" width="130" :show-overflow-tooltip="true" />
        <el-table-column label="操作状态" align="center" prop="status">
          <template #default="scope">
            <dict-tag :options="sys_common_status" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="操作日期" align="center" prop="operTime" width="180" sortable="custom" :sort-orders="['descending', 'ascending']">
          <template #default="scope">
            <span>{{ proxy.parseTime(scope.row.operTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column
          label="消耗时间"
          align="center"
          prop="costTime"
          width="110"
          :show-overflow-tooltip="true"
          sortable="custom"
          :sort-orders="['descending', 'ascending']"
        >
          <template #default="scope">
            <span>{{ scope.row.costTime }}毫秒</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" fixed="right" align="center" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="详细" placement="top">
              <el-button v-hasPermi="['monitor:operLog:query']" link type="primary" icon="View" @click="handleView(scope.row)"> </el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>
    <!-- 操作日志详细 -->
    <OperInfoDialog ref="operInfoDialogRef" />
  </div>
</template>

<script setup name="OperLog" lang="ts">
import { list, delOperLog, cleanOperLog } from '@/api/monitor/operLog';
import { OperLogForm, OperLogQuery, OperLogVO } from '@/api/monitor/operLog/types';
import OperInfoDialog from './oper-info-dialog.vue';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_oper_type, sys_common_status } = toDictRefs(
  (proxy?.useDict('sys_oper_type', 'sys_common_status') ?? {}) as Record<'sys_oper_type' | 'sys_common_status', DictDataOption[]>
);

const operLogList = ref<OperLogVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<number | string>>([]);
const multiple = ref(true);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);
const defaultSort = ref<{ prop: string; order: 'descending' | 'ascending' }>({ prop: 'operTime', order: 'descending' });

const operLogTableRef = ref<ElTableInstance>();
const queryFormRef = ref<ElFormInstance>();

const data = reactive<PageData<OperLogForm, OperLogQuery>>({
  form: {
    operId: undefined,
    title: '',
    businessType: 0,
    businessTypes: undefined,
    method: '',
    requestMethod: '',
    operatorType: 0,
    operName: '',
    deptName: '',
    operUrl: '',
    operIp: '',
    operLocation: '',
    operParam: '',
    jsonResult: '',
    status: 0,
    errorMsg: '',
    operTime: '',
    costTime: 0
  },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    operIp: '',
    title: '',
    operName: '',
    businessType: '',
    status: '',
    orderByColumn: defaultSort.value.prop,
    isAsc: defaultSort.value.order
  },
  rules: {}
});

const { queryParams, form } = toRefs(data);

/** 查询登录日志 */
const getList = async () => {
  loading.value = true;
  const res = await list(proxy?.addDateRange(queryParams.value, dateRange.value));
  operLogList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 操作日志类型字典翻译 */
const typeFormat = (row: OperLogForm) => {
  return proxy?.selectDictLabel(sys_oper_type.value, row.businessType) ?? '';
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  queryParams.value.pageNum = 1;
  operLogTableRef.value?.sort(defaultSort.value.prop, defaultSort.value.order);
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: OperLogVO[]) => {
  ids.value = selection.map((item) => item.operId);
  multiple.value = !selection.length;
};
/** 排序触发事件 */
const handleSortChange = (column: { prop: string; order: 'descending' | 'ascending' | null }) => {
  if (!column.prop || !column.order) {
    return;
  }
  queryParams.value.orderByColumn = column.prop;
  queryParams.value.isAsc = column.order;
  getList();
};

const operInfoDialogRef = ref<InstanceType<typeof OperInfoDialog>>();
/** 详细按钮操作 */
const handleView = (row: OperLogVO) => {
  operInfoDialogRef.value.openDialog(row);
};

/** 删除按钮操作 */
const handleDelete = async (row?: OperLogVO) => {
  const operIds = row?.operId || ids.value;
  await proxy?.$modal.confirm('是否确认删除日志编号为"' + operIds + '"的数据项?');
  await delOperLog(operIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

/** 清空按钮操作 */
const handleClean = async () => {
  await proxy?.$modal.confirm('是否确认清空所有操作日志数据项?');
  await cleanOperLog();
  await getList();
  proxy?.$modal.msgSuccess('清空成功');
};

/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'monitor/operLog/export',
    {
      ...queryParams.value
    },
    `config_${new Date().getTime()}.xlsx`
  );
};
onMounted(() => {
  getList();
});
</script>

// infoq-scaffold-frontend-react/src/pages/monitor/operLog/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { DeleteOutlined, DownloadOutlined, EyeOutlined, ReloadOutlined, SearchOutlined, WarningOutlined } from '@ant-design/icons';
import { Button, Card, Col, DatePicker, Form, Input, Row, Select, Space, Table, Tooltip } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import type { SortOrder, SorterResult } from 'antd/es/table/interface';
import type { Dayjs } from 'dayjs';
import useDictOptions from '@/hooks/useDictOptions';
import { cleanOperLog, delOperLog, list } from '@/api/monitor/operLog';
import type { OperLogQuery, OperLogVO } from '@/api/monitor/operLog/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import OperInfoDialog from '@/pages/monitor/operLog/oper-info-dialog';
import modal from '@/utils/modal';
import { addDateRange } from '@/utils/scaffold';
import { download } from '@/utils/request';

const initialQuery: OperLogQuery = {
  pageNum: 1,
  pageSize: 10,
  operIp: '',
  title: '',
  operName: '',
  businessType: '',
  status: '',
  orderByColumn: 'operTime',
  isAsc: 'descending'
};

const defaultSortColumn = 'operTime';

const toBackendSortOrder = (order?: SortOrder) => {
  if (order === 'ascend') {
    return 'ascending';
  }
  if (order === 'descend') {
    return 'descending';
  }
  return undefined;
};

const toAntSortOrder = (value?: string): SortOrder | undefined => {
  if (value === 'ascending') {
    return 'ascend';
  }
  if (value === 'descending') {
    return 'descend';
  }
  return undefined;
};

const formatRange = (range: [Dayjs, Dayjs] | null) =>
  range ? [range[0].format('YYYY-MM-DD HH:mm:ss'), range[1].format('YYYY-MM-DD HH:mm:ss')] : [];

export default function OperLogPage() {
  const [query, setQuery] = useState<OperLogQuery>(initialQuery);
  const [dateRange, setDateRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [listData, setListData] = useState<OperLogVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [detailOpen, setDetailOpen] = useState(false);
  const [activeRecord, setActiveRecord] = useState<OperLogVO | null>(null);
  const dict = useDictOptions('sys_oper_type', 'sys_common_status');

  const loadList = useCallback(async (nextQuery: OperLogQuery, nextRange: [Dayjs, Dayjs] | null) => {
    setLoading(true);
    try {
      const response = await list(addDateRange({ ...nextQuery }, formatRange(nextRange)));
      setListData(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadList(initialQuery, null);
  }, [loadList]);

  const columns: ColumnsType<OperLogVO> = [
    {
      title: '日志编号',
      dataIndex: 'operId',
      align: 'center'
    },
    {
      title: '系统模块',
      dataIndex: 'title',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作类型',
      dataIndex: 'businessType',
      align: 'center',
      render: (value: number) => <DictTag options={dict.sys_oper_type || []} value={String(value)} />
    },
    {
      title: '操作人员',
      dataIndex: 'operName',
      width: 110,
      align: 'center',
      ellipsis: true,
      sorter: true,
      sortDirections: ['descend', 'ascend'],
      sortOrder: query.orderByColumn === 'operName' ? toAntSortOrder(query.isAsc) : undefined
    },
    {
      title: '部门',
      dataIndex: 'deptName',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作地址',
      dataIndex: 'operIp',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作状态',
      dataIndex: 'status',
      align: 'center',
      render: (value: number) => <DictTag options={dict.sys_common_status || []} value={String(value)} />
    },
    {
      title: '操作日期',
      dataIndex: 'operTime',
      width: 180,
      align: 'center',
      sorter: true,
      sortDirections: ['descend', 'ascend'],
      sortOrder: query.orderByColumn === 'operTime' ? toAntSortOrder(query.isAsc) : undefined
    },
    {
      title: '消耗时间',
      dataIndex: 'costTime',
      width: 110,
      align: 'center',
      sorter: true,
      sortDirections: ['descend', 'ascend'],
      sortOrder: query.orderByColumn === 'costTime' ? toAntSortOrder(query.isAsc) : undefined,
      render: (value: number) => `${value}毫秒`
    },
    {
      title: '操作',
      key: 'action',
      width: 110,
      align: 'center',
      fixed: 'right',
      render: (_, record) => (
        <Tooltip title="详细">
          <Button
            className="table-action-link"
            type="link"
            icon={<EyeOutlined />}
            onClick={() => {
              setActiveRecord(record);
              setDetailOpen(true);
            }}
          />
        </Tooltip>
      )
    }
  ];

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="操作地址" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入操作地址"
                    value={query.operIp}
                    onChange={(event) => setQuery((prev) => ({ ...prev, operIp: event.target.value }))}
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="系统模块" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入系统模块"
                    value={query.title}
                    onChange={(event) => setQuery((prev) => ({ ...prev, title: event.target.value }))}
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="操作人员" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入操作人员"
                    value={query.operName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, operName: event.target.value }))}
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="类型" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="操作类型"
                    value={query.businessType || undefined}
                    options={(dict.sys_oper_type || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, businessType: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="操作状态"
                    value={query.status || undefined}
                    options={(dict.sys_common_status || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="操作时间" style={{ width: '100%', marginBottom: 12 }}>
                  <DatePicker.RangePicker
                    showTime
                    style={{ width: '100%' }}
                    value={dateRange}
                    onChange={(value) => setDateRange((value as [Dayjs, Dayjs]) || null)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button
                      type="primary"
                      icon={<SearchOutlined />}
                      onClick={() => {
                        const next = { ...query, pageNum: 1 };
                        setQuery(next);
                        loadList(next, dateRange);
                      }}
                    >
                      搜索
                    </Button>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => {
                        const resetQuery = {
                          ...initialQuery,
                          orderByColumn: defaultSortColumn,
                          isAsc: 'descending'
                        };
                        setQuery(resetQuery);
                        setDateRange(null);
                        loadList(resetQuery, null);
                      }}
                    >
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            <Button
              className="btn-plain-danger"
              icon={<DeleteOutlined />}
              disabled={selectedIds.length === 0}
              onClick={async () => {
                const confirmed = await modal.confirm(`是否确认删除日志编号为 "${selectedIds.join(',')}" 的数据项？`);
                if (!confirmed) {
                  return;
                }
                await delOperLog(selectedIds);
                modal.msgSuccess('删除成功');
                setSelectedIds([]);
                loadList(query, dateRange);
              }}
            >
              删除
            </Button>
            <Button
              className="btn-plain-danger"
              icon={<WarningOutlined />}
              onClick={async () => {
                const confirmed = await modal.confirm('是否确认清空所有操作日志数据项？');
                if (!confirmed) {
                  return;
                }
                await cleanOperLog();
                modal.msgSuccess('清空成功');
                loadList(query, dateRange);
              }}
            >
              清空
            </Button>
            <Button
              className="btn-plain-warning"
              icon={<DownloadOutlined />}
              onClick={() =>
                download(
                  '/monitor/operLog/export',
                  addDateRange({ ...query }, formatRange(dateRange)),
                  `operLog_${Date.now()}.xlsx`
                )
              }
            >
              导出
            </Button>
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query, dateRange)} />
          </div>
        </div>

        <Table<OperLogVO>
          rowKey="operId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={listData}
          pagination={false}
          onChange={(_, __, sorter) => {
            const currentSorter = (Array.isArray(sorter) ? sorter[0] : sorter) as SorterResult<OperLogVO> | undefined;
            const nextOrderByColumn = currentSorter?.field ? String(currentSorter.field) : defaultSortColumn;
            const nextIsAsc = toBackendSortOrder(currentSorter?.order) || 'descending';
            const next = {
              ...query,
              pageNum: 1,
              orderByColumn: nextOrderByColumn,
              isAsc: nextIsAsc
            };
            setQuery(next);
            loadList(next, dateRange);
          }}
          rowSelection={{
            selectedRowKeys: selectedIds,
            columnWidth: 50,
            onChange: (keys) => setSelectedIds(keys as Array<string | number>)
          }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next, dateRange);
          }}
        />
      </Card>

      <OperInfoDialog open={detailOpen} record={activeRecord} onClose={() => setDetailOpen(false)} />
    </Space>
  );
}
