// infoq-scaffold-frontend-vue/src/views/monitor/operLog/oper-info-dialog.vue
<template>
  <el-dialog v-model="open" title="操作日志详细" width="700px" append-to-body close-on-click-modal @closed="info = null">
    <el-descriptions v-if="info" :column="1" border>
      <el-descriptions-item label="操作状态">
        <template #default>
          <el-tag v-if="info.status === 0" type="success">正常</el-tag>
          <el-tag v-else-if="info.status === 1" type="danger">失败</el-tag>
        </template>
      </el-descriptions-item>
      <el-descriptions-item label="登录信息">
        <template #default> {{ info.operName }} / {{ info.deptName }} / {{ info.operIp }} / {{ info.operLocation }} </template>
      </el-descriptions-item>
      <el-descriptions-item label="请求信息">
        <template #default> {{ info.requestMethod }} {{ info.operUrl }} </template>
      </el-descriptions-item>
      <el-descriptions-item label="操作模块">
        <template #default> {{ info.title }} / {{ typeFormat(info) }} </template>
      </el-descriptions-item>
      <el-descriptions-item label="操作方法">
        <template #default>
          {{ info.method }}
        </template>
      </el-descriptions-item>
      <el-descriptions-item label="请求参数">
        <template #default>
          <div class="max-h-300px overflow-y-auto">
            <VueJsonPretty :data="formatToJsonObject(info.operParam)" />
          </div>
        </template>
      </el-descriptions-item>
      <el-descriptions-item label="返回参数">
        <template #default>
          <div class="max-h-300px overflow-y-auto">
            <VueJsonPretty :data="formatToJsonObject(info.jsonResult)" />
          </div>
        </template>
      </el-descriptions-item>
      <el-descriptions-item label="消耗时间">
        <template #default>
          <span> {{ info.costTime }}ms </span>
        </template>
      </el-descriptions-item>
      <el-descriptions-item label="操作时间">
        <template #default> {{ proxy.parseTime(info.operTime) }}</template>
      </el-descriptions-item>
      <el-descriptions-item v-if="info.status === 1" label="异常信息">
        <template #default>
          <span class="text-danger"> {{ info.errorMsg }}</span>
        </template>
      </el-descriptions-item>
    </el-descriptions>
  </el-dialog>
</template>

<script setup lang="ts">
import type { OperLogForm } from '@/api/monitor/operLog/types';
import VueJsonPretty from 'vue-json-pretty';
import 'vue-json-pretty/lib/styles.css';
import { toDictRefs } from '@/utils/dict';

const open = ref(false);
const info = ref<OperLogForm | null>(null);
function openDialog(row: OperLogForm) {
  info.value = row;
  open.value = true;
}

function closeDialog() {
  open.value = false;
}

defineExpose({
  openDialog,
  closeDialog
});

/**
 * json转为对象
 * @param data 原始数据
 */
function formatToJsonObject(data: string) {
  try {
    return JSON.parse(data);
  } catch (error) {
    return data;
  }
}

/**
 * 字典信息
 */
const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_oper_type } = toDictRefs((proxy?.useDict('sys_oper_type') ?? {}) as Record<'sys_oper_type', DictDataOption[]>);
const typeFormat = (row: OperLogForm) => {
  return proxy?.selectDictLabel(sys_oper_type.value, row.businessType) ?? '';
};
</script>

<style lang="scss" scoped>
/**
label宽度固定
*/
:deep(.el-descriptions__label) {
  min-width: 100px;
}
/**
文字超过 换行显示
*/
:deep(.el-descriptions__content) {
  max-width: 300px;
}
</style>

// infoq-scaffold-frontend-react/src/pages/monitor/operLog/oper-info-dialog.tsx
import { Card, Descriptions, Modal, Tag, Typography } from 'antd';
import useDictOptions from '@/hooks/useDictOptions';
import type { OperLogVO } from '@/api/monitor/operLog/types';

type OperInfoDialogProps = {
  open?: boolean;
  record?: OperLogVO | null;
  onClose?: () => void;
};

const formatJsonBlock = (value?: string) => {
  if (!value) {
    return '-';
  }

  try {
    return JSON.stringify(JSON.parse(value), null, 2);
  } catch {
    return value;
  }
};

const contentNode = (record?: OperLogVO | null, businessTypeLabel?: string) => {
  if (!record) {
    return (
      <Typography.Paragraph type="secondary">
        请从操作日志列表中选择一条记录查看详情。
      </Typography.Paragraph>
    );
  }

  return (
    <>
      <Descriptions
        bordered
        column={1}
        size="small"
        styles={{
          label: { minWidth: 100 },
          content: { maxWidth: 300, whiteSpace: 'normal', wordBreak: 'break-all' }
        }}
      >
        <Descriptions.Item label="操作状态">
          {record.status === 0 ? <Tag color="success">正常</Tag> : <Tag color="error">失败</Tag>}
        </Descriptions.Item>
        <Descriptions.Item label="登录信息">
          {[record.operName, record.deptName, record.operIp, record.operLocation].filter(Boolean).join(' / ') || '-'}
        </Descriptions.Item>
        <Descriptions.Item label="请求信息">
          {[record.requestMethod, record.operUrl].filter(Boolean).join(' ') || '-'}
        </Descriptions.Item>
        <Descriptions.Item label="操作模块">
          {[record.title, businessTypeLabel].filter(Boolean).join(' / ') || '-'}
        </Descriptions.Item>
        <Descriptions.Item label="操作方法">{record.method || '-'}</Descriptions.Item>
        <Descriptions.Item label="请求参数">
          <div style={{ maxHeight: 300, overflowY: 'auto' }}>
            <pre style={{ whiteSpace: 'pre-wrap', margin: 0 }}>{formatJsonBlock(record.operParam)}</pre>
          </div>
        </Descriptions.Item>
        <Descriptions.Item label="返回参数">
          <div style={{ maxHeight: 300, overflowY: 'auto' }}>
            <pre style={{ whiteSpace: 'pre-wrap', margin: 0 }}>{formatJsonBlock(record.jsonResult)}</pre>
          </div>
        </Descriptions.Item>
        <Descriptions.Item label="消耗时间">{record.costTime}ms</Descriptions.Item>
        <Descriptions.Item label="操作时间">{record.operTime || '-'}</Descriptions.Item>
        {record.status === 1 && (
          <Descriptions.Item label="异常信息">
            <span style={{ color: '#ff4d4f' }}>{record.errorMsg || '-'}</span>
          </Descriptions.Item>
        )}
      </Descriptions>
    </>
  );
};

export default function OperInfoDialog({ open, record, onClose }: OperInfoDialogProps) {
  const dict = useDictOptions('sys_oper_type');
  const businessTypeLabel = (dict.sys_oper_type || []).find((item) => item.value === String(record?.businessType))?.label;

  if (typeof open === 'undefined') {
    return <Card title="操作日志详细">{contentNode(record, businessTypeLabel)}</Card>;
  }

  return (
    <Modal width={700} footer={null} open={open} title="操作日志详细" onCancel={onClose}>
      {contentNode(record, businessTypeLabel)}
    </Modal>
  );
}
