// infoq-scaffold-frontend-vue/src/views/system/role/selectUser.vue
<template>
  <el-row>
    <el-dialog v-model="visible" title="选择用户" width="800px" top="5vh" append-to-body>
      <el-form ref="queryFormRef" :model="queryParams" :inline="true">
        <el-form-item label="用户名称" prop="userName">
          <el-input v-model="queryParams.userName" placeholder="请输入用户名称" clearable @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item label="手机号码" prop="phonenumber">
          <el-input v-model="queryParams.phonenumber" placeholder="请输入手机号码" clearable @keyup.enter="handleQuery" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
          <el-button icon="Refresh" @click="resetQuery">重置</el-button>
        </el-form-item>
      </el-form>
      <el-row>
        <el-table ref="tableRef" border :data="userList" height="260px" @row-click="clickRow" @selection-change="handleSelectionChange">
          <el-table-column type="selection" width="55"></el-table-column>
          <el-table-column label="用户名称" prop="userName" :show-overflow-tooltip="true" />
          <el-table-column label="用户昵称" prop="nickName" :show-overflow-tooltip="true" />
          <el-table-column label="邮箱" prop="email" :show-overflow-tooltip="true" />
          <el-table-column label="手机" prop="phonenumber" :show-overflow-tooltip="true" />
          <el-table-column label="状态" align="center" prop="status">
            <template #default="scope">
              <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
            </template>
          </el-table-column>
          <el-table-column label="创建时间" align="center" prop="createTime" width="180">
            <template #default="scope">
              <span>{{ proxy.parseTime(scope.row.createTime) }}</span>
            </template>
          </el-table-column>
        </el-table>
        <pagination v-if="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
      </el-row>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="handleSelectUser">确 定</el-button>
          <el-button @click="visible = false">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </el-row>
</template>

<script setup name="SelectUser" lang="ts">
import { authUserSelectAll, unallocatedUserList } from '@/api/system/role';
import { UserVO } from '@/api/system/user/types';
import { UserQuery } from '@/api/system/user/types';
import { toDictRefs } from '@/utils/dict';

const props = defineProps({
  roleId: {
    type: [Number, String],
    required: true
  }
});

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable } = toDictRefs((proxy?.useDict('sys_normal_disable') ?? {}) as Record<'sys_normal_disable', DictDataOption[]>);

const userList = ref<UserVO[]>([]);
const visible = ref(false);
const total = ref(0);
const userIds = ref<Array<string | number>>([]);

const queryParams = reactive<UserQuery>({
  pageNum: 1,
  pageSize: 10,
  roleId: undefined,
  userName: undefined,
  phonenumber: undefined
});

const tableRef = ref<ElTableInstance>();
const queryFormRef = ref<ElFormInstance>();

const show = () => {
  queryParams.roleId = props.roleId;
  getList();
  visible.value = true;
};

/**
 * 选择行
 */
const clickRow = (row: UserVO) => {
  // ele的bug
  tableRef.value?.toggleRowSelection(row, false);
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: UserVO[]) => {
  userIds.value = selection.map((item: UserVO) => item.userId);
};

/** 查询数据 */
const getList = async () => {
  const res = await unallocatedUserList(queryParams);
  userList.value = res.rows;
  total.value = res.total;
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  getList();
};

const emit = defineEmits(['ok']);
/**选择授权用户操作 */
const handleSelectUser = async () => {
  const roleId = queryParams.roleId;
  const ids = userIds.value.join(',');
  if (ids == '') {
    proxy?.$modal.msgError('请选择要分配的用户');
    return;
  }
  await authUserSelectAll({ roleId, userIds: ids });
  proxy?.$modal.msgSuccess('分配成功');
  emit('ok');
  visible.value = false;
};
// 暴露
defineExpose({
  show
});
</script>

// infoq-scaffold-frontend-react/src/pages/system/role/selectUser.tsx
import { useEffect, useMemo, useState } from 'react';
import { ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Form, Input, Modal, Space, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import useDictOptions from '@/hooks/useDictOptions';
import { authUserSelectAll, unallocatedUserList } from '@/api/system/role';
import type { UserQuery, UserVO } from '@/api/system/user/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import modal from '@/utils/modal';

type SelectUserProps = {
  roleId?: string;
  open?: boolean;
  onClose?: () => void;
  onOk?: () => void;
};

const initialQuery: UserQuery = {
  pageNum: 1,
  pageSize: 10,
  roleId: '',
  userName: '',
  phonenumber: '',
  status: '',
  deptId: '',
  userIds: undefined
};

export default function SelectUser({ roleId, open, onClose, onOk }: SelectUserProps) {
  const [query, setQuery] = useState<UserQuery>(initialQuery);
  const [loading, setLoading] = useState(false);
  const [list, setList] = useState<UserVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const dict = useDictOptions('sys_normal_disable');

  const visible = open ?? true;

  const loadList = async (nextQuery: UserQuery) => {
    setLoading(true);
    try {
      const response = await unallocatedUserList(nextQuery);
      setList(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!visible || !roleId) {
      return;
    }
    const next = {
      ...initialQuery,
      roleId
    };
    setQuery(next);
    setSelectedIds([]);
    loadList(next);
  }, [roleId, visible]);

  const columns = useMemo<ColumnsType<UserVO>>(
    () => [
      {
        title: '用户名称',
        dataIndex: 'userName'
      },
      {
        title: '用户昵称',
        dataIndex: 'nickName'
      },
      {
        title: '邮箱',
        dataIndex: 'email',
        ellipsis: true
      },
      {
        title: '手机',
        dataIndex: 'phonenumber'
      },
      {
        title: '状态',
        dataIndex: 'status',
        render: (value: string) => <DictTag options={dict.sys_normal_disable || []} value={value} />
      },
      {
        title: '创建时间',
        dataIndex: 'createTime',
        width: 180
      }
    ],
    [dict.sys_normal_disable]
  );

  const handleConfirm = async () => {
    if (!query.roleId || selectedIds.length === 0) {
      modal.msgError('请选择要分配的用户');
      return;
    }
    await authUserSelectAll({
      roleId: query.roleId,
      userIds: selectedIds.join(',')
    });
    modal.msgSuccess('分配成功');
    onOk?.();
    onClose?.();
  };

  if (typeof open === 'undefined') {
    return <Modal open title="选择用户" footer={null} onCancel={onClose} />;
  }

  return (
    <Modal width={800} open={visible} title="选择用户" onCancel={onClose} onOk={handleConfirm}>
      <Form layout="inline" className="query-form" style={{ marginBottom: 12 }}>
        <Form.Item label="用户名称">
          <Input
            allowClear
            value={query.userName}
            onChange={(event) => setQuery((prev) => ({ ...prev, userName: event.target.value }))}
            placeholder="请输入用户名称"
            onPressEnter={() => {
              const next = { ...query, pageNum: 1 };
              setQuery(next);
              loadList(next);
            }}
          />
        </Form.Item>
        <Form.Item label="手机号码">
          <Input
            allowClear
            value={query.phonenumber}
            onChange={(event) => setQuery((prev) => ({ ...prev, phonenumber: event.target.value }))}
            placeholder="请输入手机号码"
            onPressEnter={() => {
              const next = { ...query, pageNum: 1 };
              setQuery(next);
              loadList(next);
            }}
          />
        </Form.Item>
        <Form.Item>
          <Space>
            <Button
              type="primary"
              icon={<SearchOutlined />}
              onClick={() => {
                const next = { ...query, pageNum: 1 };
                setQuery(next);
                loadList(next);
              }}
            >
              搜索
            </Button>
            <Button
              icon={<ReloadOutlined />}
              onClick={() => {
                const next = { ...initialQuery, roleId: roleId || '' };
                setQuery(next);
                loadList(next);
              }}
            >
              重置
            </Button>
          </Space>
        </Form.Item>
      </Form>

      <Table<UserVO>
        rowKey="userId"
        loading={loading}
        bordered
        columns={columns}
        dataSource={list}
        scroll={{ y: 260 }}
        onRow={(record) => ({
          onClick: () => {
            setSelectedIds((current) =>
              current.includes(record.userId)
                ? current.filter((item) => item !== record.userId)
                : [...current, record.userId]
            );
          }
        })}
        pagination={false}
        rowSelection={{
          selectedRowKeys: selectedIds,
          onChange: (keys) => setSelectedIds(keys as Array<string | number>)
        }}
      />

      <Pagination
        total={total}
        page={query.pageNum}
        limit={query.pageSize}
        onPageChange={({ page, limit }) => {
          const next = { ...query, pageNum: page, pageSize: limit };
          setQuery(next);
          loadList(next);
        }}
      />
    </Modal>
  );
}
