// infoq-scaffold-frontend-react/src/pages/system/user/profile/index.tsx
import { useEffect, useState } from 'react';
import { Card, Col, Row, Tabs, theme } from 'antd';
import type { UserVO } from '@/api/system/user/types';
import type { OnlineVO } from '@/api/monitor/online/types';
import { getOnline } from '@/api/monitor/online';
import { getUserProfile } from '@/api/system/user';
import UserAvatar from '@/pages/system/user/profile/userAvatar';
import UserInfo from '@/pages/system/user/profile/userInfo';
import ResetPwd from '@/pages/system/user/profile/resetPwd';
import OnlineDevice from '@/pages/system/user/profile/onlineDevice';
import SvgIcon from '@/components/SvgIcon';
import { useSettingsStore } from '@/store/modules/settings';

type ProfileState = {
  user: Partial<UserVO>;
  roleGroup: string;
  postGroup: string;
  devices: OnlineVO[];
};

const initialState: ProfileState = {
  user: {},
  roleGroup: '',
  postGroup: '',
  devices: []
};

export default function ProfilePage() {
  const [state, setState] = useState<ProfileState>(initialState);
  const dark = useSettingsStore((state) => state.dark);
  const {
    token: { colorBorderSecondary, colorText, colorTextHeading }
  } = theme.useToken();

  const profileItems = [
    { icon: 'user', label: '用户名称', value: state.user.userName },
    { icon: 'phone', label: '手机号码', value: state.user.phonenumber },
    { icon: 'email', label: '用户邮箱', value: state.user.email },
    {
      icon: 'tree',
      label: '所属部门',
      value: state.user.deptName ? `${state.user.deptName} / ${state.postGroup || ''}` : ''
    },
    { icon: 'peoples', label: '所属角色', value: state.roleGroup },
    { icon: 'date', label: '创建日期', value: state.user.createTime }
  ];

  const loadProfile = async () => {
    const response = await getUserProfile();
    setState((prev) => ({
      ...prev,
      user: response.data?.user || {},
      roleGroup: response.data?.roleGroup || '',
      postGroup: response.data?.postGroup || ''
    }));
  };

  const loadDevices = async () => {
    const response = await getOnline();
    setState((prev) => ({
      ...prev,
      devices: response.rows || []
    }));
  };

  useEffect(() => {
    loadProfile();
    loadDevices();
  }, []);

  const listBorderColor = dark ? colorBorderSecondary : '#f0f0f0';
  const listTextColor = dark ? colorText : '#606266';
  const listLabelColor = dark ? colorTextHeading : '#303133';

  return (
    <Row gutter={20}>
      <Col xs={24} lg={6}>
        <Card title="个人信息">
          <div style={{ textAlign: 'center' }}>
            <UserAvatar avatar={state.user.avatar} onUploaded={loadProfile} />
          </div>
          <ul
            style={{
              listStyle: 'none',
              padding: 0,
              margin: '16px 0 0',
              borderTop: `1px solid ${listBorderColor}`
            }}
          >
            {profileItems.map((item) => (
              <li
                key={item.label}
                style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  justifyContent: 'space-between',
                  gap: 16,
                  padding: '10px 0',
                  borderBottom: `1px solid ${listBorderColor}`,
                  fontSize: 14,
                  color: listTextColor
                }}
              >
                <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6, whiteSpace: 'nowrap', color: listLabelColor }}>
                  <SvgIcon iconClass={item.icon} size={14} />
                  {item.label}
                </span>
                <span style={{ textAlign: 'right' }}>{item.value || ''}</span>
              </li>
            ))}
          </ul>
        </Card>
      </Col>
      <Col xs={24} lg={18}>
        <Card title="基本资料">
          <Tabs
            items={[
              {
                key: 'userinfo',
                label: '基本资料',
                children: <UserInfo user={state.user} onUpdated={loadProfile} />
              },
              {
                key: 'resetPwd',
                label: '修改密码',
                children: <ResetPwd />
              },
              {
                key: 'onlineDevice',
                label: '在线设备',
                children: <OnlineDevice devices={state.devices} onChanged={loadDevices} />
              }
            ]}
          />
        </Card>
      </Col>
    </Row>
  );
}

// infoq-scaffold-frontend-vue/src/views/system/user/profile/index.vue
<template>
  <div class="p-2">
    <el-row :gutter="20">
      <el-col :span="6" :xs="24">
        <el-card class="box-card">
          <template #header>
            <div class="clearfix">
              <span>个人信息</span>
            </div>
          </template>
          <div>
            <div class="text-center">
              <userAvatar />
            </div>
            <ul class="list-group list-group-striped">
              <li class="list-group-item">
                <svg-icon icon-class="user" />用户名称
                <div class="pull-right">{{ state.user.userName }}</div>
              </li>
              <li class="list-group-item">
                <svg-icon icon-class="phone" />手机号码
                <div class="pull-right">{{ state.user.phonenumber }}</div>
              </li>
              <li class="list-group-item">
                <svg-icon icon-class="email" />用户邮箱
                <div class="pull-right">{{ state.user.email }}</div>
              </li>
              <li class="list-group-item">
                <svg-icon icon-class="tree" />所属部门
                <div v-if="state.user.deptName" class="pull-right">{{ state.user.deptName }} / {{ state.postGroup }}</div>
              </li>
              <li class="list-group-item">
                <svg-icon icon-class="peoples" />所属角色
                <div class="pull-right">{{ state.roleGroup }}</div>
              </li>
              <li class="list-group-item">
                <svg-icon icon-class="date" />创建日期
                <div class="pull-right">{{ state.user.createTime }}</div>
              </li>
            </ul>
          </div>
        </el-card>
      </el-col>
      <el-col :span="18" :xs="24">
        <el-card>
          <template #header>
            <div class="clearfix">
              <span>基本资料</span>
            </div>
          </template>
          <el-tabs v-model="activeTab">
            <el-tab-pane label="基本资料" name="userinfo">
              <userInfo :user="userForm" />
            </el-tab-pane>
            <el-tab-pane label="修改密码" name="resetPwd">
              <resetPwd />
            </el-tab-pane>
            <el-tab-pane label="在线设备" name="onlineDevice">
              <onlineDevice :devices="state.devices" />
            </el-tab-pane>
          </el-tabs>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script setup name="Profile" lang="ts">
import UserAvatar from './userAvatar.vue';
import UserInfo from './userInfo.vue';
import ResetPwd from './resetPwd.vue';
import OnlineDevice from './onlineDevice.vue';
import { getUserProfile } from '@/api/system/user';
import { getOnline } from '@/api/monitor/online';
import { UserVO } from '@/api/system/user/types';

const activeTab = ref('userinfo');
interface State {
  user: Partial<UserVO>;
  roleGroup: string;
  postGroup: string;
  auths: any;
  devices: any;
}
const state = ref<State>({
  user: {},
  roleGroup: '',
  postGroup: '',
  auths: [],
  devices: []
});

const userForm = ref({});

const getUser = async () => {
  const res = await getUserProfile();
  state.value.user = res.data.user;
  userForm.value = { ...res.data.user };
  state.value.roleGroup = res.data.roleGroup;
  state.value.postGroup = res.data.postGroup;
};

const getOnlines = async () => {
  const res = await getOnline();
  state.value.devices = res.rows;
};

onMounted(() => {
  getUser();
  getOnlines();
});
</script>
