// infoq-scaffold-frontend-react/src/pages/system/user/profile/onlineDevice.tsx
import { DeleteOutlined } from '@ant-design/icons';
import { Button, Table, Tooltip } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import useDictOptions from '@/hooks/useDictOptions';
import { delOnline } from '@/api/monitor/online';
import type { OnlineVO } from '@/api/monitor/online/types';
import DictTag from '@/components/DictTag';
import { parseTime } from '@/utils/scaffold';
import modal from '@/utils/modal';

type OnlineDeviceProps = {
  devices?: OnlineVO[];
  onChanged?: () => void;
};

export default function OnlineDevice({ devices, onChanged }: OnlineDeviceProps) {
  const dict = useDictOptions('sys_device_type');
  const dataSource = devices || [];

  const columns: ColumnsType<OnlineVO> = [
    {
      title: '设备类型',
      dataIndex: 'deviceType',
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_device_type || []} value={value} />
    },
    {
      title: '主机',
      dataIndex: 'ipaddr',
      align: 'center',
      ellipsis: true
    },
    {
      title: '登录地点',
      dataIndex: 'loginLocation',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作系统',
      dataIndex: 'os',
      align: 'center',
      ellipsis: true
    },
    {
      title: '浏览器',
      dataIndex: 'browser',
      align: 'center',
      ellipsis: true
    },
    {
      title: '登录时间',
      dataIndex: 'loginTime',
      width: 180,
      align: 'center',
      render: (value: string | number) => parseTime(value) || '-'
    },
    {
      title: '操作',
      key: 'action',
      width: 120,
      align: 'center',
      render: (_, record) => (
        <Tooltip title="删除">
          <Button
            danger
            type="link"
            icon={<DeleteOutlined />}
            onClick={async () => {
              const confirmed = await modal.confirm('删除设备后，在该设备登录需要重新进行验证');
              if (!confirmed) {
                return;
              }
              await delOnline(record.tokenId);
              modal.msgSuccess('删除成功');
              await onChanged?.();
            }}
          />
        </Tooltip>
      )
    }
  ];

  return <Table<OnlineVO> bordered rowKey="tokenId" dataSource={dataSource} columns={columns} pagination={false} />;
}

// infoq-scaffold-frontend-vue/src/views/system/user/profile/onlineDevice.vue
<template>
  <div>
    <el-table :data="devices" border style="width: 100%; height: 100%; font-size: 14px">
      <el-table-column label="设备类型" align="center">
        <template #default="scope">
          <dict-tag :options="sys_device_type" :value="scope.row.deviceType" />
        </template>
      </el-table-column>
      <el-table-column label="主机" align="center" prop="ipaddr" :show-overflow-tooltip="true" />
      <el-table-column label="登录地点" align="center" prop="loginLocation" :show-overflow-tooltip="true" />
      <el-table-column label="操作系统" align="center" prop="os" :show-overflow-tooltip="true" />
      <el-table-column label="浏览器" align="center" prop="browser" :show-overflow-tooltip="true" />
      <el-table-column label="登录时间" align="center" prop="loginTime" width="180">
        <template #default="scope">
          <span>{{ proxy.parseTime(scope.row.loginTime) }}</span>
        </template>
      </el-table-column>
      <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
        <template #default="scope">
          <el-tooltip content="删除" placement="top">
            <el-button link type="primary" icon="Delete" @click="handldDelOnline(scope.row)"> </el-button>
          </el-tooltip>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script setup name="Online" lang="ts">
import { delOnline } from '@/api/monitor/online';
import { propTypes } from '@/utils/propTypes';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_device_type } = toDictRefs((proxy?.useDict('sys_device_type') ?? {}) as Record<'sys_device_type', DictDataOption[]>);

const props = defineProps({
  devices: propTypes.any.isRequired
});
const devices = computed(() => props.devices);

/** 删除按钮操作 */
const handldDelOnline = async (row: { tokenId: string | number }) => {
  try {
    await ElMessageBox.confirm('删除设备后，在该设备登录需要重新进行验证');
    const res = await delOnline(row.tokenId);
    if (res.code === 200) {
      proxy?.$modal.msgSuccess('删除成功');
      proxy?.$tab.refreshPage();
    } else {
      proxy?.$modal.msgError(res.msg);
    }
  } catch {}
};
</script>
