// infoq-scaffold-frontend-weapp-vue/src/pages/system-users/form/index.vue
<template>
  <view class="page-wrap">
    <view class="form-section">
      <!-- 基本信息 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">基本信息</text>
        </view>
        <view class="card-content" style="padding: 0">
          <picker
            mode="selector"
            :range="deptOptions.map(d => `${'· '.repeat(d._depth)}${d.label}`)"
            @change="handleDeptChange"
          >
            <view class="picker-input-aligned">
              <text class="picker-label">所属部门</text>
              <view class="picker-value-container">
                <text :class="['picker-value', !selectedDept ? 'placeholder' : '']">
                  {{ selectedDeptLabel }}
                </text>
                <AppIcon name="chevron-right" size="32" class="picker-arrow" />
              </view>
            </view>
          </picker>

          <view class="form-item-modern">
            <text class="form-label">登录账号</text>
            <input class="form-input-plain" v-model="form.userName" placeholder="请输入登录账号" :disabled="isEdit" placeholder-style="color: #94a3b8" />
          </view>
          
          <view class="form-item-modern">
            <text class="form-label">用户昵称</text>
            <input class="form-input-plain" v-model="form.nickName" placeholder="请输入用户昵称" placeholder-style="color: #94a3b8" />
          </view>
          
          <view class="form-item-modern" v-if="!isEdit">
            <text class="form-label">初始密码</text>
            <input class="form-input-plain" type="password" v-model="form.password" placeholder="请输入初始密码" placeholder-style="color: #94a3b8" />
          </view>
          
          <view class="form-item-modern">
            <text class="form-label">手机号码</text>
            <input class="form-input-plain" v-model="form.phonenumber" placeholder="请输入手机号码" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>

      <!-- 用户属性 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">用户属性</text>
        </view>
        <view class="card-content">
          <view class="form-item-vertical">
            <text class="item-label">性别</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in sexOptions"
                :key="item.value"
                :class="['radio-option-item', form.sex === item.value ? 'active' : '']"
                @click="form.sex = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.sex === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>

          <view class="form-item-vertical" style="margin-top: 32rpx">
            <text class="item-label">状态</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in statusOptions"
                :key="item.value"
                :class="['radio-option-item', form.status === item.value ? 'active' : '']"
                @click="form.status = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.status === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 分配角色 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">分配角色</text>
        </view>
        <view class="card-content">
          <view class="checkbox-group-vertical">
            <view
              v-for="item in roleOptions"
              :key="String(item.roleId)"
              :class="['checkbox-item', isRoleSelected(item.roleId) ? 'active' : '']"
              @click="toggleRole(item.roleId)"
            >
              <view :class="['checkbox-box', isRoleSelected(item.roleId) ? 'checked' : '']">
                <view v-if="isRoleSelected(item.roleId)" class="checkbox-inner" />
              </view>
              <text class="checkbox-label">{{ item.roleName }}</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 操作按钮 -->
    <view class="action-section">
      <button class="primary-btn save-btn" :loading="submitting" @click="save">保 存</button>
      <button class="secondary-btn cancel-btn" @click="backOr(routes.users)">取 消</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import AppIcon from '@/components/AppIcon.vue';
import { 
  addUser, 
  getUser, 
  updateUser, 
  getDicts, 
  toDictOptions, 
  deptTreeSelectForUser, 
  flattenTree, 
  optionSelectRoles,
  type UserForm, 
  type DictOption, 
  type FlatTreeItem, 
  type DeptTreeVO, 
  type RoleVO 
} from '@/api';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { backOr, routes } from '@/utils/navigation';
import { handlePageError, showSuccess } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

const sessionStore = useSessionStore();
const userId = ref('');
const submitting = ref(false);
const statusOptions = ref<DictOption[]>([]);
const sexOptions = ref<DictOption[]>([]);
const deptOptions = ref<Array<FlatTreeItem<DeptTreeVO>>>([]);
const roleOptions = ref<RoleVO[]>([]);

const form = reactive<UserForm>({
  userName: '',
  password: '',
  nickName: '',
  phonenumber: '',
  email: '',
  sex: '0',
  status: '0',
  remark: '',
  deptId: undefined,
  roleIds: [],
  postIds: []
});

const isEdit = computed(() => Boolean(userId.value));

const selectedDept = computed(() => deptOptions.value.find(d => Number(d.id) === form.deptId));
const selectedDeptLabel = computed(() => selectedDept.value ? `${'· '.repeat(selectedDept.value._depth)}${selectedDept.value.label}` : '请选择部门');

const handleDeptChange = (e: any) => {
  const index = e.detail.value;
  form.deptId = Number(deptOptions.value[index].id);
};

const isRoleSelected = (roleId: any) => (form.roleIds || []).includes(String(roleId));
const toggleRole = (roleId: any) => {
  const idStr = String(roleId);
  const current = form.roleIds || [];
  if (current.includes(idStr)) {
    form.roleIds = current.filter(id => id !== idStr);
  } else {
    form.roleIds = [...current, idStr];
  }
};

const loadData = async () => {
  try {
    const [statusRes, sexRes, deptRes, roleRes] = await Promise.all([
      getDicts('sys_normal_disable'),
      getDicts('sys_user_sex'),
      deptTreeSelectForUser(),
      optionSelectRoles()
    ]);

    statusOptions.value = toDictOptions(statusRes.data);
    sexOptions.value = toDictOptions(sexRes.data);
    deptOptions.value = flattenTree(deptRes.data);
    roleOptions.value = roleRes.data || [];

    if (userId.value) {
      const response = await getUser(userId.value);
      const { user, roleIds, postIds } = response.data;
      Object.assign(form, {
        ...user,
        userId: String(user.userId),
        roleIds: (roleIds || []).map(String),
        postIds: (postIds || []).map(String)
      });
    }
  } catch (error) {
    await handlePageError(error, '数据加载失败');
  }
};

const save = async () => {
  if (!form.deptId) {
    await uni.showToast({ title: '请选择所属部门', icon: 'none' });
    return;
  }
  if (!form.userName?.trim()) {
    await uni.showToast({ title: '请输入登录账号', icon: 'none' });
    return;
  }
  if (!form.nickName?.trim()) {
    await uni.showToast({ title: '请输入用户昵称', icon: 'none' });
    return;
  }
  if (!isEdit.value && !form.password?.trim()) {
    await uni.showToast({ title: '请输入初始密码', icon: 'none' });
    return;
  }

  submitting.value = true;
  try {
    if (!ensureAuthenticated()) return;
    await sessionStore.loadSession();
    if (isEdit.value) {
      await updateUser(form);
    } else {
      await addUser(form);
    }
    await showSuccess('保存成功');
    backOr(routes.users);
  } catch (error) {
    await handlePageError(error, '保存失败');
  } finally {
    submitting.value = false;
  }
};

onLoad((query) => {
  if (!ensureAuthenticated()) return;
  userId.value = String(query?.userId || '').trim();
  loadData();
});
</script>

<style lang="scss">
@import '@/styles/common.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/system-users/form/index.tsx
import { View, Text, Picker } from '@tarojs/components';
import Taro, { useDidShow, useRouter } from '@tarojs/taro';
import {
  addUser,
  deptTreeSelectForUser,
  flattenTree,
  getDicts,
  getUser,
  optionSelectRoles,
  toDictOptions,
  updateUser,
  type DeptTreeVO,
  type DictOption,
  type FlatTreeItem,
  type RoleVO,
  type UserForm
} from '@/api';
import { useState } from 'react';
import { AtButton, AtInput } from 'taro-ui';
import { routes } from '../../../utils/navigation';
import { handlePageError, showSuccess } from '../../../utils/ui';
import { useSessionStore } from '../../../store/session';
import './index.scss';

const createForm = (): UserForm => ({
  userId: undefined,
  deptId: undefined,
  userName: '',
  nickName: '',
  password: '',
  phonenumber: '',
  email: '',
  sex: '2',
  status: '0',
  remark: '',
  postIds: [],
  roleIds: []
});

const normalizeIdList = (items?: Array<string | number>) => (items || []).map((item) => String(item));

export default function UserFormPage() {
  const router = useRouter();
  const userId = router.params.userId;
  const loadSession = useSessionStore((state) => state.loadSession);
  const [form, setForm] = useState<UserForm>(createForm());
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [sexOptions, setSexOptions] = useState<DictOption[]>([]);
  const [deptOptions, setDeptOptions] = useState<Array<FlatTreeItem<DeptTreeVO>>>([]);
  const [roleOptions, setRoleOptions] = useState<RoleVO[]>([]);
  const [submitting, setSubmitting] = useState(false);

  const loadData = async () => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }

      const [statusRes, sexRes, deptRes, roleRes] = await Promise.all([
        getDicts('sys_normal_disable'),
        getDicts('sys_user_sex'),
        deptTreeSelectForUser(),
        optionSelectRoles()
      ]);

      setStatusOptions(toDictOptions(statusRes.data));
      setSexOptions(toDictOptions(sexRes.data));
      setDeptOptions(flattenTree(deptRes.data));
      setRoleOptions(roleRes.data || []);

      if (userId) {
        const response = await getUser(userId);
        const { user, roleIds, postIds } = response.data;
        setForm({
          userId: String(user.userId),
          deptId: user.deptId,
          userName: user.userName,
          nickName: user.nickName,
          phonenumber: user.phonenumber,
          email: user.email,
          sex: user.sex,
          status: user.status,
          remark: user.remark,
          roleIds: normalizeIdList(roleIds),
          postIds: normalizeIdList(postIds)
        });
      }
    } catch (error) {
      await handlePageError(error, '加载失败');
    }
  };

  useDidShow(() => {
    void loadData();
  });

  const handleSave = async () => {
    if (!form.deptId) {
      await Taro.showToast({ title: '请选择所属部门', icon: 'none' });
      return;
    }
    if (!form.userName?.trim()) {
      await Taro.showToast({ title: '请输入登录账号', icon: 'none' });
      return;
    }
    if (!form.nickName?.trim()) {
      await Taro.showToast({ title: '请输入用户昵称', icon: 'none' });
      return;
    }
    if (!userId && !form.password?.trim()) {
      await Taro.showToast({ title: '请输入初始密码', icon: 'none' });
      return;
    }
    if (!(form.roleIds || []).length) {
      await Taro.showToast({ title: '至少选择一个角色', icon: 'none' });
      return;
    }

    setSubmitting(true);
    try {
      const payload = { ...form };
      if (userId) {
        await updateUser(payload);
      } else {
        await addUser(payload);
      }
      await showSuccess(userId ? '用户已更新' : '用户已创建');
      Taro.navigateBack();
    } catch (error) {
      await handlePageError(error, '保存失败');
    } finally {
      setSubmitting(false);
    }
  };

  const selectedDept = deptOptions.find(d => Number(d.id) === form.deptId);
  const selectedDeptLabel = selectedDept ? `${'· '.repeat(selectedDept._depth)}${selectedDept.label}` : '请选择部门';

  return (
    <View className="user-form-container">
      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <Picker
              mode="selector"
              range={deptOptions.map(d => `${'· '.repeat(d._depth)}${d.label}`)}
              onChange={(e) => {
                const index = Number(e.detail.value);
                setForm(prev => ({ ...prev, deptId: Number(deptOptions[index].id) }));
              }}
            >
              <View className="at-input picker-input-aligned">
                <View className="at-input__container">
                  <View className="at-input__title">所属部门</View>
                  <View className="at-input__input picker-value-container">
                    <Text className={`picker-value ${!selectedDept ? 'placeholder' : ''}`}>
                      {selectedDeptLabel}
                    </Text>
                    <View className="at-icon at-icon-chevron-right picker-arrow"></View>
                  </View>
                </View>
              </View>
            </Picker>

            <AtInput
              name="userName"
              title="登录账号"
              placeholder="请输入登录账号"
              value={form.userName || ''}
              onChange={(v) => { setForm(p => ({ ...p, userName: String(v) })); return v; }}
            />
            <AtInput
              name="nickName"
              title="用户昵称"
              placeholder="请输入用户昵称"
              value={form.nickName || ''}
              onChange={(v) => { setForm(p => ({ ...p, nickName: String(v) })); return v; }}
            />
            {!userId && (
              <AtInput
                name="password"
                title="初始密码"
                type="password"
                placeholder="请输入初始密码"
                value={form.password || ''}
                onChange={(v) => { setForm(p => ({ ...p, password: String(v) })); return v; }}
              />
            )}
            <AtInput
              name="phonenumber"
              title="手机号码"
              type="phone"
              placeholder="请输入手机号码"
              value={form.phonenumber || ''}
              onChange={(v) => { setForm(p => ({ ...p, phonenumber: String(v) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">用户属性</Text>
          </View>
          <View className="card-content">
            <View className="form-item-vertical">
              <Text className="item-label">性别</Text>
              <View className="radio-options-horizontal">
                {sexOptions.map((item) => (
                  <View
                    key={item.value}
                    className={`radio-option-item ${form.sex === item.value ? 'active' : ''}`}
                    onClick={() => setForm((prev) => ({ ...prev, sex: item.value }))}
                  >
                    <View className="radio-circle">
                      {form.sex === item.value && <View className="radio-inner" />}
                    </View>
                    <Text className="radio-label">{item.label}</Text>
                  </View>
                ))}
              </View>
            </View>

            <View className="form-item-vertical" style={{ marginTop: '32rpx' }}>
              <Text className="item-label">状态</Text>
              <View className="radio-options-horizontal">
                {statusOptions.map((item) => (
                  <View
                    key={item.value}
                    className={`radio-option-item ${form.status === item.value ? 'active' : ''}`}
                    onClick={() => setForm((prev) => ({ ...prev, status: item.value }))}
                  >
                    <View className="radio-circle">
                      {form.status === item.value && <View className="radio-inner" />}
                    </View>
                    <Text className="radio-label">{item.label}</Text>
                  </View>
                ))}
              </View>
            </View>
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">分配角色</Text>
          </View>
          <View className="card-content">
            <View className="checkbox-group-vertical">
              {roleOptions.map((item) => {
                const isSelected = (form.roleIds || []).includes(String(item.roleId));
                return (
                  <View
                    key={String(item.roleId)}
                    className={`checkbox-item ${isSelected ? 'active' : ''}`}
                    onClick={() => {
                      const nextIds = isSelected
                        ? (form.roleIds || []).filter(id => id !== String(item.roleId))
                        : [...(form.roleIds || []), String(item.roleId)];
                      setForm(prev => ({ ...prev, roleIds: nextIds }));
                    }}
                  >
                    <View className={`checkbox-box ${isSelected ? 'checked' : ''}`}>
                      {isSelected && <View className="checkbox-inner" />}
                    </View>
                    <Text className="checkbox-label">{item.roleName}</Text>
                  </View>
                );
              })}
            </View>
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" loading={submitting} onClick={() => void handleSave()}>
          保存用户
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => Taro.navigateBack()}>
          返回
        </AtButton>
      </View>
    </View>
  );
}
