// infoq-scaffold-frontend-weapp-vue/src/pages/notices/index.vue
<template>
  <view class="list-container">
    <view class="search-section">
      <view class="search-card">
        <view class="search-field">
          <text class="field-label">公告标题</text>
          <view class="field-input-box">
            <input v-model="query.noticeTitle" placeholder="按公告标题过滤" placeholder-style="color: #94a3b8" />
          </view>
        </view>
        <view class="search-actions">
  <button class="secondary-btn search-action-btn" @click="handleReset">重置</button>
  <button class="primary-btn search-action-btn" @click="handleSearch">查询</button>
</view>
      </view>
    </view>

    <view class="list-content">
      <EmptyNotice v-if="!canList" message="当前账号没有访问权限" />
      <EmptyNotice v-else-if="rows.length === 0" message="未查询到相关公告" />
      
      <template v-if="canList">
        <RecordCard
          v-for="item in rows"
          :key="item.noticeId"
          icon="message"
          :title="item.noticeTitle || '未知公告'"
          :status-color="item.status === '0' ? '#52c41a' : '#ff4d4f'"
          :actions="getNoticeActions(item)"
        >
          <template #extra>
            <StatusTag 
              :label="getDictLabel(typeOptions, item.noticeType) || '未知'" 
              type="info"
            />
          </template>
          
          <KeyValueList
            :items="[
              { label: '状态', value: item.status === '0' ? '正常' : '停用' },
              { label: '创建人', value: item.createByName || '-' },
              { label: '创建时间', value: formatDateTime(item.createTime) }
            ]"
          />
        </RecordCard>

        <PaginationBar
          :current="query.pageNum"
          :page-size="query.pageSize"
          :total="total"
          @change="handlePageChange"
        />
      </template>
    </view>

    <FabButton v-if="canAdd" @click="openCreate" />
    
    <BottomNav active="admin" />
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import { 
  delNotice, 
  formatDateTime, 
  getDictLabel, 
  getDicts, 
  listNotice, 
  toDictOptions, 
  type DictOption, 
  type NoticeVO 
} from '@/api';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { navigate, routes } from '@/utils/navigation';
import { handlePageError, showSuccess } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

import BottomNav from '@/components/BottomNav.vue';
import EmptyNotice from '@/components/EmptyNotice.vue';
import KeyValueList from '@/components/KeyValueList.vue';
import PaginationBar from '@/components/PaginationBar.vue';
import RecordCard from '@/components/RecordCard.vue';
import StatusTag from '@/components/StatusTag.vue';
import FabButton from '@/components/FabButton.vue';

const sessionStore = useSessionStore();
const rows = ref<NoticeVO[]>([]);
const total = ref(0);
const typeOptions = ref<DictOption[]>([]);

const query = reactive({
  pageNum: 1,
  pageSize: 10,
  noticeTitle: '',
  createByName: '',
  status: '',
  noticeType: ''
});

const canList = computed(() => sessionStore.permissions.includes('system:notice:list'));
const canAdd = computed(() => sessionStore.permissions.includes('system:notice:add'));
const canEdit = computed(() => sessionStore.permissions.includes('system:notice:edit'));
const canRemove = computed(() => sessionStore.permissions.includes('system:notice:remove'));

const loadData = async () => {
  if (!ensureAuthenticated()) {
    return;
  }
  try {
    await sessionStore.loadSession();
    const [typeResponse, listResponse] = await Promise.all([
      getDicts('sys_notice_type'),
      canList.value ? listNotice(query) : Promise.resolve({ rows: [], total: 0 })
    ]);
    typeOptions.value = toDictOptions(typeResponse.data);
    rows.value = listResponse.rows || [];
    total.value = listResponse.total || 0;
  } catch (error) {
    await handlePageError(error, '公告列表加载失败');
  }
};

const handleSearch = () => {
  query.pageNum = 1;
  void loadData();
};

const handleReset = () => {
  query.pageNum = 1;
  query.noticeTitle = '';
  void loadData();
};

const handlePageChange = (page: number) => {
  query.pageNum = page;
  void loadData();
};

const openCreate = () => {
  navigate(routes.noticeForm);
};

const openDetail = (noticeId: number) => {
  navigate(`${routes.noticeDetail}?noticeId=${noticeId}`);
};

const openEdit = (noticeId: number) => {
  navigate(`${routes.noticeForm}?noticeId=${noticeId}`);
};

const handleDelete = async (noticeId: number) => {
  const res = await uni.showModal({
    title: '确认删除',
    content: `确定删除公告 #${noticeId} 吗？`
  });
  if (!res.confirm) return;
  
  try {
    await delNotice(noticeId);
    await showSuccess('公告已删除');
    await loadData();
  } catch (error) {
    await handlePageError(error, '公告删除失败');
  }
};

const getNoticeActions = (item: NoticeVO) => {
  const actions = [];
  actions.push({ title: '详情', onClick: () => openDetail(item.noticeId!) });
  if (canEdit.value) {
    actions.push({ title: '编辑', onClick: () => openEdit(item.noticeId!) });
  }
  if (canRemove.value) {
    actions.push({ 
      title: '删除', 
      onClick: () => handleDelete(item.noticeId!),
      danger: true
    });
  }
  return actions;
};

onShow(() => {
  void loadData();
});
</script>

<style lang="scss">
@import './index.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/notices/index.tsx
import { View } from '@tarojs/components';
import Taro, { useDidShow } from '@tarojs/taro';
import {
  delNotice,
  formatDateTime,
  getDictLabel,
  getDicts,
  listNotice,
  stripHtml,
  toDictOptions,
  type DictOption,
  type NoticeQuery,
  type NoticeVO
} from '@/api';
import { useState } from 'react';
import { AtButton, AtInput } from 'taro-ui';
import BottomNav from '../../components/bottom-nav';
import { EmptyNotice, KeyValueList, PaginationBar, RecordCard, StatusTag, FabButton } from '../../components/taro-ui-kit';
import { navigate, routes } from '../../utils/navigation';
import { handlePageError, showSuccess } from '../../utils/ui';
import { useSessionStore } from '../../store/session';
import './index.scss';

const createQuery = (pageNum = 1): NoticeQuery => ({
  pageNum,
  pageSize: 10,
  noticeTitle: '',
  createByName: '',
  status: '',
  noticeType: ''
});

export default function NoticesPage() {
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);
  const [query, setQuery] = useState<NoticeQuery>(createQuery());
  const [list, setList] = useState<NoticeVO[]>([]);
  const [total, setTotal] = useState(0);
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [typeOptions, setTypeOptions] = useState<DictOption[]>([]);

  const canList = permissions.includes('system:notice:list');
  const canQuery = permissions.includes('system:notice:query');
  const canEdit = permissions.includes('system:notice:edit');
  const canAdd = permissions.includes('system:notice:add');
  const canRemove = permissions.includes('system:notice:remove');

  const loadPage = async (nextQuery = query) => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }
      const [statusResponse, typeResponse, listResponse] = await Promise.all([
        getDicts('sys_notice_status'),
        getDicts('sys_notice_type'),
        canList ? listNotice(nextQuery) : Promise.resolve({ rows: [], total: 0 })
      ]);
      setStatusOptions(toDictOptions(statusResponse.data));
      setTypeOptions(toDictOptions(typeResponse.data));
      setList(listResponse.rows || []);
      setTotal(listResponse.total || 0);
    } catch (error) {
      await handlePageError(error, '公告列表加载失败');
    }
  };

  useDidShow(() => {
    void loadPage();
  });

  const handleDelete = async (noticeId: number) => {
    const modal = await Taro.showModal({
      title: '确认删除',
      content: `确定删除公告 #${noticeId} 吗？`
    });
    if (!modal.confirm) return;
    try {
      await delNotice(noticeId);
      await showSuccess('删除成功');
      await loadPage({ ...query });
    } catch (error) {
      await handlePageError(error, '公告删除失败');
    }
  };

  return (
    <View className="list-container">
      <View className="search-section">
        <View className="search-card">
          <AtInput
            clear
            name="noticeTitle"
            placeholder="按公告标题过滤"
            title="搜索标题"
            value={query.noticeTitle || ''}
            onChange={(value) => {
              setQuery((prev) => ({ ...prev, noticeTitle: String(value) }));
              return value;
            }}
          />
          <View className="search-actions">
            <AtButton
              className="search-action-btn"
              type="secondary"
              onClick={() => {
                const nextQuery = createQuery();
                setQuery(nextQuery);
                void loadPage(nextQuery);
              }}
            >
              重置
            </AtButton>
            <AtButton
              className="search-action-btn"
              type="primary"
              onClick={() => void loadPage({ ...query, pageNum: 1 })}
            >
              查询
            </AtButton>
          </View>
        </View>
      </View>

      <View className="list-content">
        {!canList && <EmptyNotice message="当前账号没有访问权限" />}
        {canList && list.length === 0 && <EmptyNotice message="未查询到相关公告" />}
        {canList && list.map((item) => (
          <RecordCard
            key={item.noticeId}
            icon="message"
            title={item.noticeTitle}
            statusColor={item.noticeType === '1' ? '#1677ff' : '#faad14'}
            extra={
              <StatusTag 
                label={getDictLabel(typeOptions, item.noticeType) || '公告'} 
                type={item.noticeType === '1' ? 'info' : 'warning'} 
              />
            }
            actions={[
              ...(canQuery ? [{ onClick: () => navigate(`${routes.noticeDetail}?noticeId=${item.noticeId}`), title: '详情' }] : []),
              ...(canEdit ? [{ onClick: () => navigate(`${routes.noticeForm}?noticeId=${item.noticeId}`), title: '编辑' }] : []),
              ...(canRemove ? [{ 
                onClick: () => void handleDelete(item.noticeId), 
                title: '删除',
                danger: true 
              }] : [])
            ]}
          >
            <KeyValueList
              items={[
                { label: '状态', value: getDictLabel(statusOptions, item.status) || '-' },
                { label: '摘要', value: stripHtml(item.noticeContent).slice(0, 50) + (stripHtml(item.noticeContent).length > 50 ? '...' : '') || '-' },
                { label: '发布人', value: item.createByName || '系统' },
                { label: '发布时间', value: item.createTime ? formatDateTime(item.createTime).split(' ')[0] : '-' }
              ]}
            />
          </RecordCard>
        ))}

        {canList && (
          <PaginationBar
            current={query.pageNum}
            pageSize={query.pageSize}
            total={total}
            onChange={(page) => {
              const nextQuery = { ...query, pageNum: page };
              setQuery(nextQuery);
              void loadPage(nextQuery);
            }}
          />
        )}
      </View>

      {canAdd && <FabButton onClick={() => navigate(routes.noticeForm)} />}
      
      <BottomNav active="admin" />
    </View>
  );
}
