// infoq-scaffold-frontend-weapp-vue/src/pages/system-posts/form/index.vue
<template>
  <view class="page-wrap">
    <view class="form-section">
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">基本信息</text>
        </view>
        <view class="card-content" style="padding: 0">
          <view class="form-item-modern">
            <text class="form-label">岗位名称</text>
            <input class="form-input-plain" v-model="form.postName" placeholder="请输入岗位名称" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">岗位编码</text>
            <input class="form-input-plain" v-model="form.postCode" placeholder="请输入岗位编码" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">显示排序</text>
            <input class="form-input-plain" v-model.number="form.postSort" type="number" placeholder="请输入排序" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>

      <view class="card-container">
        <view class="card-header">
          <text class="card-title">状态与备注</text>
        </view>
        <view class="card-content">
          <view class="form-item-vertical">
            <text class="item-label">状态</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in statusOptions"
                :key="item.value"
                :class="['radio-option-item', form.status === item.value ? 'active' : '']"
                @click="form.status = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.status === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>

          <view class="form-item-vertical" style="margin-top: 32rpx">
            <text class="item-label">备注说明</text>
            <textarea class="form-textarea" v-model="form.remark" placeholder="请输入备注" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>
    </view>

    <!-- 操作按钮 -->
    <view class="action-section">
      <button class="primary-btn save-btn" :loading="submitting" @click="save">保 存</button>
      <button class="secondary-btn cancel-btn" @click="backOr(routes.posts)">取 消</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { addPost, getPost, updatePost, getDicts, toDictOptions, type PostForm, type DictOption } from '@/api';
import { ensureAuthenticated } from '@/composables/use-auth-guard';
import { backOr, routes } from '@/utils/navigation';
import { handlePageError, showSuccess } from '@/utils/ui';
import { useSessionStore } from '@/store/session';

const sessionStore = useSessionStore();
const postId = ref('');
const submitting = ref(false);
const statusOptions = ref<DictOption[]>([]);

const form = reactive<PostForm>({
  postName: '',
  postCode: '',
  postSort: 0,
  status: '0',
  remark: ''
});

const isEdit = computed(() => Boolean(postId.value));

const loadData = async () => {
  try {
    const statusRes = await getDicts('sys_normal_disable');
    statusOptions.value = toDictOptions(statusRes.data);

    if (postId.value) {
      const response = await getPost(postId.value);
      Object.assign(form, response.data || {});
    }
  } catch (error) {
    await handlePageError(error, '岗位信息加载失败');
  }
};

const save = async () => {
  if (!form.postName?.trim() || !form.postCode?.trim()) {
    await uni.showToast({ title: '岗位名称和编码不能为空', icon: 'none' });
    return;
  }
  submitting.value = true;
  try {
    if (!ensureAuthenticated()) return;
    await sessionStore.loadSession();
    if (isEdit.value) {
      form.postId = Number(postId.value);
      await updatePost(form);
    } else {
      await addPost(form);
    }
    await showSuccess('保存成功');
    backOr(routes.posts);
  } catch (error) {
    await handlePageError(error, '岗位保存失败');
  } finally {
    submitting.value = false;
  }
};

onLoad((query) => {
  if (!ensureAuthenticated()) return;
  postId.value = String(query?.userId || query?.postId || '').trim();
  loadData();
});
</script>

<style lang="scss">
@import '@/styles/common.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/system-posts/form/index.tsx
import { View, Text, Picker } from '@tarojs/components';
import Taro, { useDidShow, useRouter } from '@tarojs/taro';
import {
  addPost,
  getDicts,
  getPost,
  deptTreeSelectForPost,
  flattenTree,
  toDictOptions,
  updatePost,
  type DictOption,
  type PostForm,
  type DeptTreeVO,
  type FlatTreeItem
} from '@/api';
import { useState } from 'react';
import { AtButton, AtInput, AtTextarea } from 'taro-ui';
import { handlePageError, showSuccess } from '../../../utils/ui';
import { useSessionStore } from '../../../store/session';
import { routes } from '../../../utils/navigation';
import './index.scss';

const createForm = (): PostForm => ({
  postId: undefined,
  deptId: undefined,
  postCode: '',
  postName: '',
  postCategory: '',
  postSort: 1,
  status: '0',
  remark: ''
});

export default function PostFormPage() {
  const router = useRouter();
  const postId = router.params.postId;
  const loadSession = useSessionStore((state) => state.loadSession);
  const [form, setForm] = useState<PostForm>(createForm());
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [deptOptions, setDeptOptions] = useState<Array<FlatTreeItem<DeptTreeVO>>>([]);
  const [submitting, setSubmitting] = useState(false);

  const loadData = async () => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }

      const [statusRes, deptRes] = await Promise.all([
        getDicts('sys_normal_disable'),
        deptTreeSelectForPost()
      ]);
      setStatusOptions(toDictOptions(statusRes.data));
      setDeptOptions(flattenTree(deptRes.data));

      if (postId) {
        const response = await getPost(postId);
        const data = response.data;
        setForm({
          postId: data.postId,
          deptId: data.deptId,
          postCode: data.postCode,
          postName: data.postName,
          postCategory: data.postCategory || '',
          postSort: data.postSort,
          status: data.status || '0',
          remark: data.remark || ''
        });
      }
    } catch (error) {
      await handlePageError(error, '加载失败');
    }
  };

  useDidShow(() => {
    void loadData();
  });

  const handleSave = async () => {
    if (!form.deptId) {
      await Taro.showToast({ title: '请选择归属部门', icon: 'none' });
      return;
    }
    if (!form.postName.trim()) {
      await Taro.showToast({ title: '请输入岗位名称', icon: 'none' });
      return;
    }
    if (!form.postCode.trim()) {
      await Taro.showToast({ title: '请输入岗位编码', icon: 'none' });
      return;
    }

    setSubmitting(true);
    try {
      if (postId) {
        await updatePost(form);
      } else {
        await addPost(form);
      }
      await showSuccess(postId ? '岗位已更新' : '岗位已创建');
      Taro.navigateBack();
    } catch (error) {
      await handlePageError(error, '保存失败');
    } finally {
      setSubmitting(false);
    }
  };

  const selectedDept = deptOptions.find(d => String(d.id) === String(form.deptId));
  const selectedDeptLabel = selectedDept ? `${'· '.repeat(selectedDept._depth)}${selectedDept.label}` : '请选择归属部门';

  return (
    <View className="post-form-container">
      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <Picker
              mode="selector"
              range={deptOptions.map(d => `${'· '.repeat(d._depth)}${d.label}`)}
              onChange={(e) => {
                const index = Number(e.detail.value);
                setForm(prev => ({ ...prev, deptId: Number(deptOptions[index].id) }));
              }}
            >
              <View className="at-input picker-input-aligned">
                <View className="at-input__container">
                  <View className="at-input__title">归属部门</View>
                  <View className="at-input__input picker-value-container">
                    <Text className={`picker-value ${!selectedDept ? 'placeholder' : ''}`}>
                      {selectedDeptLabel}
                    </Text>
                    <View className="at-icon at-icon-chevron-right picker-arrow"></View>
                  </View>
                </View>
              </View>
            </Picker>

            <AtInput
              name="postName"
              title="岗位名称"
              placeholder="请输入岗位名称"
              value={form.postName}
              onChange={(v) => { setForm(p => ({ ...p, postName: String(v) })); return v; }}
            />
            <AtInput
              name="postCode"
              title="岗位编码"
              placeholder="请输入岗位编码"
              value={form.postCode}
              onChange={(v) => { setForm(p => ({ ...p, postCode: String(v) })); return v; }}
            />
            <AtInput
              name="postCategory"
              title="岗位类别"
              placeholder="请输入岗位类别"
              value={form.postCategory || ''}
              onChange={(v) => { setForm(p => ({ ...p, postCategory: String(v) })); return v; }}
            />
            <AtInput
              name="postSort"
              title="显示顺序"
              type="number"
              placeholder="请输入显示顺序"
              value={String(form.postSort)}
              onChange={(v) => { setForm(p => ({ ...p, postSort: Number(v) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">状态</Text>
          </View>
          <View className="card-content">
            <View className="radio-options-horizontal">
              {statusOptions.map((item) => (
                <View
                  key={item.value}
                  className={`radio-option-item ${form.status === item.value ? 'active' : ''}`}
                  onClick={() => setForm((prev) => ({ ...prev, status: item.value }))}
                >
                  <View className="radio-circle">
                    {form.status === item.value && <View className="radio-inner" />}
                  </View>
                  <Text className="radio-label">{item.label}</Text>
                </View>
              ))}
            </View>
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">备注</Text>
          </View>
          <View className="card-content">
            <AtTextarea
              height={200}
              count={false}
              placeholder="请输入备注说明"
              value={form.remark || ''}
              onChange={(value) => setForm((prev) => ({ ...prev, remark: value }))}
            />
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" loading={submitting} onClick={() => void handleSave()}>
          保存岗位
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => Taro.navigateBack()}>
          返回
        </AtButton>
      </View>
    </View>
  );
}
