// infoq-scaffold-frontend-react/src/pages/monitor/loginInfo/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { DeleteOutlined, DownloadOutlined, ReloadOutlined, SearchOutlined, UnlockOutlined } from '@ant-design/icons';
import { Button, Card, Col, DatePicker, Form, Input, Row, Select, Space, Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import type { SortOrder, SorterResult } from 'antd/es/table/interface';
import type { Dayjs } from 'dayjs';
import useDictOptions from '@/hooks/useDictOptions';
import { cleanLoginInfo, delLoginInfo, list, unlockLoginInfo } from '@/api/monitor/loginInfo';
import type { LoginInfoQuery, LoginInfoVO } from '@/api/monitor/loginInfo/types';
import DictTag from '@/components/DictTag';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import modal from '@/utils/modal';
import { addDateRange } from '@/utils/scaffold';
import { download } from '@/utils/request';

type LoginInfoRow = LoginInfoVO & {
  clientKey?: string;
  deviceType?: string;
};

const initialQuery: LoginInfoQuery = {
  pageNum: 1,
  pageSize: 10,
  ipaddr: '',
  userName: '',
  status: '',
  orderByColumn: 'loginTime',
  isAsc: 'descending'
};

const defaultSortColumn = 'loginTime';

const toBackendSortOrder = (order?: SortOrder) => {
  if (order === 'ascend') {
    return 'ascending';
  }
  if (order === 'descend') {
    return 'descending';
  }
  return undefined;
};

const toAntSortOrder = (value?: string): SortOrder | undefined => {
  if (value === 'ascending') {
    return 'ascend';
  }
  if (value === 'descending') {
    return 'descend';
  }
  return undefined;
};

const formatRange = (range: [Dayjs, Dayjs] | null) =>
  range ? [range[0].format('YYYY-MM-DD HH:mm:ss'), range[1].format('YYYY-MM-DD HH:mm:ss')] : [];

export default function LoginInfoPage() {
  const [query, setQuery] = useState<LoginInfoQuery>(initialQuery);
  const [dateRange, setDateRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [listData, setListData] = useState<LoginInfoRow[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [selectedNames, setSelectedNames] = useState<string[]>([]);
  const dict = useDictOptions('sys_device_type', 'sys_common_status');

  const loadList = useCallback(async (nextQuery: LoginInfoQuery, nextRange: [Dayjs, Dayjs] | null) => {
    setLoading(true);
    try {
      const response = await list(addDateRange({ ...nextQuery }, formatRange(nextRange)));
      setListData(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadList(initialQuery, null);
  }, [loadList]);

  const columns: ColumnsType<LoginInfoRow> = [
    {
      title: '访问编号',
      dataIndex: 'infoId',
      align: 'center'
    },
    {
      title: '用户名称',
      dataIndex: 'userName',
      align: 'center',
      ellipsis: true,
      sorter: true,
      sortDirections: ['descend', 'ascend'],
      sortOrder: query.orderByColumn === 'userName' ? toAntSortOrder(query.isAsc) : undefined
    },
    {
      title: '客户端',
      dataIndex: 'clientKey',
      width: 90,
      align: 'center',
      ellipsis: true
    },
    {
      title: '设备类型',
      dataIndex: 'deviceType',
      width: 90,
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_device_type || []} value={value} />
    },
    {
      title: '地址',
      dataIndex: 'ipaddr',
      align: 'center',
      ellipsis: true
    },
    {
      title: '登录地点',
      dataIndex: 'loginLocation',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作系统',
      dataIndex: 'os',
      align: 'center',
      ellipsis: true
    },
    {
      title: '浏览器',
      dataIndex: 'browser',
      align: 'center',
      ellipsis: true
    },
    {
      title: '登录状态',
      dataIndex: 'status',
      width: 90,
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_common_status || []} value={value} />
    },
    {
      title: '描述',
      dataIndex: 'msg',
      align: 'center',
      ellipsis: true
    },
    {
      title: '访问时间',
      dataIndex: 'loginTime',
      width: 180,
      align: 'center',
      sorter: true,
      sortDirections: ['descend', 'ascend'],
      sortOrder: query.orderByColumn === 'loginTime' ? toAntSortOrder(query.isAsc) : undefined
    }
  ];

  const handleDelete = async () => {
    if (selectedIds.length === 0) {
      modal.msgWarning('请选择要删除的登录日志');
      return;
    }
    const confirmed = await modal.confirm(`是否确认删除访问编号为 "${selectedIds.join(',')}" 的数据项？`);
    if (!confirmed) {
      return;
    }
    await delLoginInfo(selectedIds);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    loadList(query, dateRange);
  };

  const handleUnlock = async () => {
    if (selectedNames.length !== 1) {
      modal.msgWarning('请选择一条需要解锁的记录');
      return;
    }
    const confirmed = await modal.confirm(`是否确认解锁用户 "${selectedNames[0]}" 数据项？`);
    if (!confirmed) {
      return;
    }
    await unlockLoginInfo(selectedNames);
    modal.msgSuccess(`用户 ${selectedNames[0]} 解锁成功`);
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="登录地址" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入登录地址"
                    value={query.ipaddr}
                    onChange={(event) => setQuery((prev) => ({ ...prev, ipaddr: event.target.value }))}
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="用户名称" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入用户名称"
                    value={query.userName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, userName: event.target.value }))}
                    onPressEnter={() => {
                      const next = { ...query, pageNum: 1 };
                      setQuery(next);
                      loadList(next, dateRange);
                    }}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    style={{ width: '100%' }}
                    placeholder="登录状态"
                    value={query.status || undefined}
                    options={(dict.sys_common_status || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="登录时间" style={{ width: '100%', marginBottom: 12 }}>
                  <DatePicker.RangePicker
                    showTime
                    style={{ width: '100%' }}
                    value={dateRange}
                    onChange={(value) => setDateRange((value as [Dayjs, Dayjs]) || null)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button
                      type="primary"
                      icon={<SearchOutlined />}
                      onClick={() => {
                        const next = { ...query, pageNum: 1 };
                        setQuery(next);
                        loadList(next, dateRange);
                      }}
                    >
                      搜索
                    </Button>
                    <Button
                      icon={<ReloadOutlined />}
                      onClick={() => {
                        const resetQuery = {
                          ...initialQuery,
                          orderByColumn: defaultSortColumn,
                          isAsc: 'descending'
                        };
                        setQuery(resetQuery);
                        setDateRange(null);
                        loadList(resetQuery, null);
                      }}
                    >
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            <Button className="btn-plain-danger" icon={<DeleteOutlined />} onClick={handleDelete} disabled={selectedIds.length === 0}>
              删除
            </Button>
            <Button
              className="btn-plain-danger"
              icon={<DeleteOutlined />}
              onClick={async () => {
                const confirmed = await modal.confirm('是否确认清空所有登录日志数据项？');
                if (!confirmed) {
                  return;
                }
                await cleanLoginInfo();
                modal.msgSuccess('清空成功');
                loadList(query, dateRange);
              }}
            >
              清空
            </Button>
            <Button className="btn-plain-primary" icon={<UnlockOutlined />} onClick={handleUnlock} disabled={selectedNames.length !== 1}>
              解锁
            </Button>
            <Button
              className="btn-plain-warning"
              icon={<DownloadOutlined />}
              onClick={() =>
                download(
                  '/monitor/loginInfo/export',
                  addDateRange({ ...query }, formatRange(dateRange)),
                  `loginInfo_${Date.now()}.xlsx`
                )
              }
            >
              导出
            </Button>
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query, dateRange)} />
          </div>
        </div>

        <Table<LoginInfoRow>
          rowKey="infoId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={listData}
          pagination={false}
          onChange={(_, __, sorter) => {
            const currentSorter = (Array.isArray(sorter) ? sorter[0] : sorter) as SorterResult<LoginInfoRow> | undefined;
            const nextOrderByColumn = currentSorter?.field ? String(currentSorter.field) : defaultSortColumn;
            const nextIsAsc = toBackendSortOrder(currentSorter?.order) || 'descending';
            const next = {
              ...query,
              pageNum: 1,
              orderByColumn: nextOrderByColumn,
              isAsc: nextIsAsc
            };
            setQuery(next);
            loadList(next, dateRange);
          }}
          rowSelection={{
            selectedRowKeys: selectedIds,
            columnWidth: 55,
            onChange: (keys, rows) => {
              setSelectedIds(keys as Array<string | number>);
              setSelectedNames(rows.map((item) => String((item as LoginInfoRow).userName)));
            }
          }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next, dateRange);
          }}
        />
      </Card>
    </Space>
  );
}

// infoq-scaffold-frontend-vue/src/views/monitor/loginInfo/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true">
            <el-form-item label="登录地址" prop="ipaddr">
              <el-input v-model="queryParams.ipaddr" placeholder="请输入登录地址" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="用户名称" prop="userName">
              <el-input v-model="queryParams.userName" placeholder="请输入用户名称" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="登录状态" clearable>
                <el-option v-for="dict in sys_common_status" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item label="登录时间" style="width: 308px">
              <el-date-picker
                v-model="dateRange"
                value-format="YYYY-MM-DD HH:mm:ss"
                type="daterange"
                range-separator="-"
                start-placeholder="开始日期"
                end-placeholder="结束日期"
                :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
              ></el-date-picker>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:loginInfo:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:loginInfo:remove']" type="danger" plain icon="Delete" @click="handleClean">清空</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:loginInfo:unlock']" type="primary" plain icon="Unlock" :disabled="single" @click="handleUnlock">
              解锁
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['monitor:loginInfo:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table
        ref="loginInfoTableRef"
        v-loading="loading"
        :data="loginInfoList"
        :default-sort="defaultSort"
        border
        @selection-change="handleSelectionChange"
        @sort-change="handleSortChange"
      >
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="访问编号" align="center" prop="infoId" />
        <el-table-column
          label="用户名称"
          align="center"
          prop="userName"
          :show-overflow-tooltip="true"
          sortable="custom"
          :sort-orders="['descending', 'ascending']"
        />
        <el-table-column label="客户端" align="center" prop="clientKey" :show-overflow-tooltip="true" />
        <el-table-column label="设备类型" align="center">
          <template #default="scope">
            <dict-tag :options="sys_device_type" :value="scope.row.deviceType" />
          </template>
        </el-table-column>
        <el-table-column label="地址" align="center" prop="ipaddr" :show-overflow-tooltip="true" />
        <el-table-column label="登录地点" align="center" prop="loginLocation" :show-overflow-tooltip="true" />
        <el-table-column label="操作系统" align="center" prop="os" :show-overflow-tooltip="true" />
        <el-table-column label="浏览器" align="center" prop="browser" :show-overflow-tooltip="true" />
        <el-table-column label="登录状态" align="center" prop="status">
          <template #default="scope">
            <dict-tag :options="sys_common_status" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="描述" align="center" prop="msg" :show-overflow-tooltip="true" />
        <el-table-column label="访问时间" align="center" prop="loginTime" sortable="custom" :sort-orders="['descending', 'ascending']" width="180">
          <template #default="scope">
            <span>{{ proxy.parseTime(scope.row.loginTime) }}</span>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>
  </div>
</template>

<script setup name="LoginInfo" lang="ts">
import { list, delLoginInfo, cleanLoginInfo, unlockLoginInfo } from '@/api/monitor/loginInfo';
import { LoginInfoQuery, LoginInfoVO } from '@/api/monitor/loginInfo/types';
import { toDictRefs } from '@/utils/dict';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_device_type } = toDictRefs((proxy?.useDict('sys_device_type') ?? {}) as Record<'sys_device_type', DictDataOption[]>);
const { sys_common_status } = toDictRefs((proxy?.useDict('sys_common_status') ?? {}) as Record<'sys_common_status', DictDataOption[]>);

const loginInfoList = ref<LoginInfoVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<number | string>>([]);
const single = ref(true);
const multiple = ref(true);
const selectName = ref<Array<string>>([]);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);
const defaultSort = ref<{ prop: string; order: 'descending' | 'ascending' }>({ prop: 'loginTime', order: 'descending' });

const queryFormRef = ref<ElFormInstance>();
const loginInfoTableRef = ref<ElTableInstance>();
// 查询参数
const queryParams = ref<LoginInfoQuery>({
  pageNum: 1,
  pageSize: 10,
  ipaddr: '',
  userName: '',
  status: '',
  orderByColumn: defaultSort.value.prop,
  isAsc: defaultSort.value.order
});

/** 查询登录日志列表 */
const getList = async () => {
  loading.value = true;
  const res = await list(proxy?.addDateRange(queryParams.value, dateRange.value));
  loginInfoList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  queryParams.value.pageNum = 1;
  loginInfoTableRef.value?.sort(defaultSort.value.prop, defaultSort.value.order);
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: LoginInfoVO[]) => {
  ids.value = selection.map((item) => item.infoId);
  multiple.value = !selection.length;
  single.value = selection.length != 1;
  selectName.value = selection.map((item) => item.userName);
};
/** 排序触发事件 */
const handleSortChange = (column: { prop: string; order: 'descending' | 'ascending' | null }) => {
  if (!column.prop || !column.order) {
    return;
  }
  queryParams.value.orderByColumn = column.prop;
  queryParams.value.isAsc = column.order;
  getList();
};
/** 删除按钮操作 */
const handleDelete = async (row?: LoginInfoVO) => {
  const infoIds = row?.infoId || ids.value;
  await proxy?.$modal.confirm('是否确认删除访问编号为"' + infoIds + '"的数据项?');
  await delLoginInfo(infoIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};
/** 清空按钮操作 */
const handleClean = async () => {
  await proxy?.$modal.confirm('是否确认清空所有登录日志数据项?');
  await cleanLoginInfo();
  await getList();
  proxy?.$modal.msgSuccess('清空成功');
};
/** 解锁按钮操作 */
const handleUnlock = async () => {
  const username = selectName.value;
  await proxy?.$modal.confirm('是否确认解锁用户"' + username + '"数据项?');
  await unlockLoginInfo(username);
  proxy?.$modal.msgSuccess('用户' + username + '解锁成功');
};
/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'monitor/loginInfo/export',
    {
      ...queryParams.value
    },
    `loginInfo_${new Date().getTime()}.xlsx`
  );
};

onMounted(() => {
  getList();
});
</script>
